// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, desc, eq, isNull } from "drizzle-orm";

import {
  consentRecords,
  normativeDataConsents,
} from "@/drizzle/schema";
import { writeSystemAuditLog } from "@/server/audit/write-system-audit-log";
import { controlDb } from "@/server/db/control-db";

export type ConsentPurpose =
  | "analytics"
  | "marketing_cookies"
  | "marketing_email";

export async function appendConsentRecord({
  userId,
  purpose,
  version,
  granted,
  source,
  metadata = {},
}: {
  userId: string;
  purpose: ConsentPurpose;
  version: string;
  granted: boolean;
  source: string;
  metadata?: Record<string, unknown>;
}) {
  const now = new Date();

  const [created] = await controlDb
    .insert(consentRecords)
    .values({
      userId,
      purpose,
      version,
      status: granted ? "granted" : "withdrawn",
      grantedAt: granted ? now : null,
      withdrawnAt: granted ? null : now,
      source,
      metadata,
      createdAt: now,
    })
    .returning();

  await writeSystemAuditLog({
    actorUserId: userId,
    actorRole: "USER",
    action: granted ? "consent.granted" : "consent.withdrawn",
    entityType: "consent_record",
    entityId: created.id,
    after: { purpose, version, source },
  });

  return created;
}

export async function withdrawResearchConsent(userId: string) {
  const consent = await controlDb.query.normativeDataConsents.findFirst({
    where: and(
      eq(normativeDataConsents.ownerUserId, userId),
      isNull(normativeDataConsents.withdrawnAt),
    ),
    orderBy: desc(normativeDataConsents.acceptedAt),
  });

  if (!consent) return null;

  const now = new Date();
  const [updated] = await controlDb
    .update(normativeDataConsents)
    .set({
      withdrawnAt: now,
      updatedAt: now,
      updatedBy: userId,
    })
    .where(eq(normativeDataConsents.id, consent.id))
    .returning();

  await writeSystemAuditLog({
    actorUserId: userId,
    actorRole: "USER",
    action: "research_consent.withdrawn",
    entityType: "normative_data_consent",
    entityId: consent.id,
    before: { withdrawnAt: null },
    after: { withdrawnAt: now.toISOString() },
  });

  return updated;
}
