// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, desc, eq, isNull } from "drizzle-orm";

import {
  consentRecords,
  legalAcceptances,
  legalDocuments,
  normativeDataConsents,
} from "@/drizzle/schema";
import { requireSession } from "@/server/auth/require-session";
import { controlDb } from "@/server/db/control-db";

export async function getMyPrivacyState() {
  const session = await requireSession();

  const [records, legal, research] = await Promise.all([
    controlDb
      .select()
      .from(consentRecords)
      .where(eq(consentRecords.userId, session.user.id))
      .orderBy(desc(consentRecords.createdAt)),
    controlDb
      .select({
        type: legalDocuments.type,
        version: legalDocuments.version,
        acceptedAt: legalAcceptances.acceptedAt,
      })
      .from(legalAcceptances)
      .innerJoin(
        legalDocuments,
        eq(legalDocuments.id, legalAcceptances.documentId),
      )
      .where(eq(legalAcceptances.userId, session.user.id))
      .orderBy(desc(legalAcceptances.acceptedAt)),
    controlDb.query.normativeDataConsents.findFirst({
      where: eq(normativeDataConsents.ownerUserId, session.user.id),
      orderBy: desc(normativeDataConsents.acceptedAt),
    }),
  ]);

  const latest = new Map<string, (typeof records)[number]>();
  for (const record of records) {
    if (!latest.has(record.purpose)) latest.set(record.purpose, record);
  }

  return {
    userId: session.user.id,
    legal,
    analytics: latest.get("analytics") ?? null,
    marketingCookies: latest.get("marketing_cookies") ?? null,
    marketingEmail: latest.get("marketing_email") ?? null,
    research: research ?? null,
  };
}
