// @generated by install-humanet-values-marketing.mjs
"use server";

import { revalidatePath } from "next/cache";

import { requireSession } from "@/server/auth/require-session";
import {
  appendConsentRecord,
  withdrawResearchConsent,
} from "./privacy-consent.mutations";

export async function updateMarketingEmailConsentAction(formData: FormData) {
  const session = await requireSession();
  const granted = formData.get("granted") === "true";

  await appendConsentRecord({
    userId: session.user.id,
    purpose: "marketing_email",
    version:
      process.env.MARKETING_EMAIL_CONSENT_VERSION?.trim() || "2026-08-01",
    granted,
    source: "my_privacy",
  });

  revalidatePath("/my/privacy");
}

export async function withdrawResearchConsentAction() {
  const session = await requireSession();
  await withdrawResearchConsent(session.user.id);
  revalidatePath("/my/privacy");
}
