// @generated by install-humanet-values-consultations-v5.mjs
import { NextResponse } from "next/server";
import { z } from "zod";

import { markOwnedConsultationBookingOpened } from "@/features/purchase-flow/api/consultation-booking.mutations";

const schema = z.object({
  entitlementId: z.string().uuid(),
  surface: z.string().trim().max(80).nullable().optional(),
});

export async function POST(request: Request) {
  try {
    const body = schema.parse(await request.json());
    await markOwnedConsultationBookingOpened({
      entitlementId: body.entitlementId,
      surface: body.surface ?? null,
    });
    return NextResponse.json({ ok: true });
  } catch {
    return NextResponse.json(
      { ok: false, error: "invalid_consultation" },
      { status: 400 },
    );
  }
}
