// @generated by install-humanet-values-marketing.mjs
import { getServerSession } from "next-auth";

import { authOptions } from "@/auth";
import { StartFlowPage } from "@/features/purchase-flow";
import {
  startFlowSearchParamsSchema,
} from "@/features/purchase-flow/forms/start-flow.schema";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type SearchParams = Record<string, string | string[] | undefined>;

function first(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

export default async function StartPage({
  searchParams,
}: {
  searchParams: Promise<SearchParams>;
}) {
  const raw = await searchParams;
  const parsed = startFlowSearchParamsSchema.safeParse({
    offer: first(raw.offer),
    reportType: first(raw.reportType),
    utm_source: first(raw.utm_source),
    utm_medium: first(raw.utm_medium),
    utm_campaign: first(raw.utm_campaign),
    utm_content: first(raw.utm_content),
    utm_term: first(raw.utm_term),
    ref: first(raw.ref),
    partner: first(raw.partner),
  });

  const safe = parsed.success ? parsed.data : {};
  const session = await getServerSession(authOptions);

  const passthrough = Object.fromEntries(
    Object.entries(safe)
      .filter(([key, value]) => key !== "offer" && key !== "reportType" && value)
      .map(([key, value]) => [key, String(value)]),
  );

  return (
    <StartFlowPage
      isAuthenticated={Boolean(session?.user?.id)}
      offerCode={safe.offer ?? null}
      reportType={safe.reportType ?? null}
      passthrough={passthrough}
    />
  );
}
