// @generated by install-humanet-values-marketing.mjs
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { updateConsultationEntitlementAction } from "../api/consultation-admin.actions";
import { listConsultationEntitlementsAdmin } from "../api/consultation-admin.queries";

export async function ConsultationsAdminPage() {
  const rows = await listConsultationEntitlementsAdmin();

  return (
    <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6">
      <h1 className="text-3xl font-semibold">Konsultacje z pakietów B2C</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Uprawnienia są tworzone idempotentnie po opłaceniu zamówienia.
      </p>

      <div className="mt-6 space-y-3">
        {rows.length === 0 ? (
          <div className="rounded-2xl border bg-white p-6 text-sm text-muted-foreground">
            Brak uprawnień konsultacyjnych.
          </div>
        ) : (
          rows.map((row) => (
            <article
              key={row.id}
              className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm lg:grid-cols-[1fr_auto]"
            >
              <div>
                <p className="font-semibold">{row.userEmail}</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  {row.kind} · {row.durationMinutes} min · status: {row.status}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  Zamówienie: {row.orderId} · płatność: {row.orderStatus ?? "—"}
                </p>
              </div>

              <form
                action={updateConsultationEntitlementAction}
                className="flex flex-wrap items-end gap-2"
              >
                <input type="hidden" name="entitlementId" value={row.id} />
                <label className="text-xs">
                  <span className="mb-1 block">Status</span>
                  <select
                    name="status"
                    defaultValue={row.status}
                    className="h-10 rounded-md border bg-white px-3 text-sm"
                  >
                    <option value="available">Dostępna</option>
                    <option value="booked">Umówiona</option>
                    <option value="completed">Zrealizowana</option>
                    <option value="expired">Wygasła</option>
                    <option value="cancelled">Anulowana</option>
                  </select>
                </label>
                <label className="text-xs">
                  <span className="mb-1 block">Referencja Cal.com</span>
                  <Input
                    name="bookingReference"
                    defaultValue={row.bookingReference ?? ""}
                    className="w-52"
                  />
                </label>
                <Button type="submit">Zapisz</Button>
              </form>
            </article>
          ))
        )}
      </div>
    </main>
  );
}
