// @generated by install-humanet-values-marketing.mjs
"use client";

import { trackEvent } from "@/features/consent";

export function ConsultationLink({
  href,
  durationMinutes,
  orderId,
}: {
  href: string;
  durationMinutes: number;
  orderId: string;
}) {
  const url = new URL(href);
  url.searchParams.set("metadata[orderId]", orderId);

  return (
    <a
      href={url.toString()}
      target="_blank"
      rel="noreferrer"
      onClick={() =>
        trackEvent("consultation_booking_clicked", {
          consultation_minutes: durationMinutes,
          surface: "order_success",
        })
      }
      className="inline-flex min-h-11 items-center justify-center rounded-full bg-teal-700 px-5 text-sm font-semibold text-white hover:bg-teal-800"
    >
      Umów konsultację ({durationMinutes} min)
    </a>
  );
}
