// @generated by install-humanet-values-marketing.mjs
export type AttributionTouch = {
  source: string | null;
  medium: string | null;
  campaign: string | null;
  content: string | null;
  term: string | null;
  landingPage: string;
  referrer: string | null;
  capturedAt: string;
  ref: string | null;
  partner: string | null;
};

export type AttributionSnapshot = {
  firstTouch: AttributionTouch;
  lastTouch: AttributionTouch;
};
