// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { z } from "zod";

import type { OfferCode, ReportType } from "../types/purchase-flow.types";

const nonEmpty = z.string().trim().min(1);

const rawConfigSchema = z.object({
  relationsQuestionnaireCode: nonEmpty,
  workQuestionnaireCode: nonEmpty,
  changeQuestionnaireCode: nonEmpty,
});

export type OfferDefinition = {
  code: OfferCode;
  label: string;
  description: string;
};

export type ReportDefinition = {
  code: ReportType;
  questionnaireCode: string;
  label: string;
  description: string;
};

export function getPurchaseFlowConfig() {
  const parsed = rawConfigSchema.safeParse({
    relationsQuestionnaireCode:
      process.env.HUMANET_REPORT_TYPE_RELATIONS_QUESTIONNAIRE_CODE,
    workQuestionnaireCode:
      process.env.HUMANET_REPORT_TYPE_WORK_QUESTIONNAIRE_CODE,
    changeQuestionnaireCode:
      process.env.HUMANET_REPORT_TYPE_CHANGE_QUESTIONNAIRE_CODE,
  });

  if (!parsed.success) {
    throw new Error(
      "Brakuje konfiguracji kwestionariuszy ścieżki zakupowej HUMANET. Sprawdź docs/marketing-purchase-consent-install.md.",
    );
  }

  const value = parsed.data;

  const offers: Record<OfferCode, OfferDefinition> = {
    report: {
      code: "report",
      label: "Badanie HUMANET",
      description: "Pełny raport bez konsultacji.",
    },
    report_plus_consultation: {
      code: "report_plus_consultation",
      label: "Badanie i konsultacja",
      description:
        "Pełny raport oraz konsultacja w czasie skonfigurowanym dla konkretnego produktu.",
    },
    decision_support: {
      code: "decision_support",
      label: "Wsparcie decyzji i zmiany",
      description:
        "Pełny raport oraz rozszerzona konsultacja decyzyjna skonfigurowana dla konkretnego produktu.",
    },
  };

  const reports: Record<ReportType, ReportDefinition> = {
    relations: {
      code: "relations",
      questionnaireCode: value.relationsQuestionnaireCode,
      label: "Ja i moje relacje",
      description:
        "Zrozum wzorce budowania relacji, komunikacji i reagowania na innych.",
    },
    work: {
      code: "work",
      questionnaireCode: value.workQuestionnaireCode,
      label: "Ja w pracy i współpracy",
      description:
        "Zobacz, co wpływa na Twoje decyzje, współpracę i sposób działania w pracy.",
    },
    change: {
      code: "change",
      questionnaireCode: value.changeQuestionnaireCode,
      label: "Ja w zmianie",
      description:
        "Rozpoznaj aktualny sposób przeżywania zmiany, bariery i warunki wspierające.",
    },
  };

  return { offers, reports };
}
