// @generated by install-humanet-values-marketing.mjs
import { describe, expect, it } from "vitest";

import {
  mergeReportAccessB2cOfferConfig,
  readReportAccessB2cOffer,
} from "./report-access-product-offer";

describe("report access B2C offer config", () => {
  it("preserves unrelated config keys", () => {
    const next = mergeReportAccessB2cOfferConfig({
      currentConfig: { legacy: true },
      offerCode: "report_plus_consultation",
      consultationMinutes: 75,
    });

    expect(next.legacy).toBe(true);
    expect(readReportAccessB2cOffer(next)).toEqual({
      offerCode: "report_plus_consultation",
      consultation: {
        kind: "report_consultation",
        durationMinutes: 75,
      },
    });
  });

  it("removes only B2C mapping when offer is cleared", () => {
    const next = mergeReportAccessB2cOfferConfig({
      currentConfig: {
        legacy: "keep",
        b2cOffer: { offerCode: "report", consultation: null },
      },
      offerCode: null,
    });

    expect(next).toEqual({ legacy: "keep" });
  });

  it("never creates a consultation for report-only package", () => {
    const next = mergeReportAccessB2cOfferConfig({
      currentConfig: {},
      offerCode: "report",
      consultationMinutes: 120,
    });

    expect(readReportAccessB2cOffer(next)).toEqual({
      offerCode: "report",
      consultation: null,
    });
  });
});
