// @generated by install-humanet-values-marketing.mjs
export const HUMANET_B2C_OFFER_CODES = [
  "report",
  "report_plus_consultation",
  "decision_support",
] as const;

export type HumanetB2cOfferCode =
  (typeof HUMANET_B2C_OFFER_CODES)[number];
