// @generated by install-humanet-values-marketing.mjs
import { getMyPrivacyState } from "@/features/privacy/api/privacy.queries";
import { PrivacyPage } from "@/features/privacy/components/privacy-page";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function Page() {
  const state = await getMyPrivacyState();
  return <PrivacyPage state={state} />;
}
