services:
  postgres:
    image: postgres:17-alpine
    container_name: humanet-values-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: humanet_values
      POSTGRES_PASSWORD: VALvalHUMhumPOSpos02
      POSTGRES_DB: humanet_control
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data