// @generated by install-humanet-values-marketing.mjs
import { readConsentCookie } from "./consent-cookie";

declare global {
  interface Window {
    dataLayer?: Array<Record<string, unknown> | unknown[]>;
    gtag?: (...args: unknown[]) => void;
  }
}

export function trackEvent(
  event: string,
  params: Record<string, unknown> = {},
): void {
  if (typeof window === "undefined") return;

  const version =
    process.env.NEXT_PUBLIC_CONSENT_VERSION?.trim() || "2026-08-01";

  const consent = readConsentCookie(version);

  if (!consent?.analytics) return;

  window.dataLayer = window.dataLayer || [];

  if ("ecommerce" in params) {
    window.dataLayer.push({
      ecommerce: null,
    });
  }

  window.dataLayer.push({
    event,
    ...params,
  });
}