// @generated by install-humanet-values-marketing.mjs
import { sql } from "drizzle-orm";
import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { users } from "./users";

export const consultationEntitlements = pgTable(
  "consultation_entitlements",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orderId: uuid("order_id"),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    source: varchar("source", { length: 30 })
      .notNull()
      .default("package"),
    kind: varchar("kind", { length: 60 }).notNull(),
    durationMinutes: integer("duration_minutes").notNull(),

    status: varchar("status", { length: 30 })
      .notNull()
      .default("available"),

    bookingProvider: varchar("booking_provider", { length: 40 })
      .notNull()
      .default("calcom"),
    bookingReference: varchar("booking_reference", { length: 255 }),

    scheduledStartAt: timestamp("scheduled_start_at", {
      withTimezone: true,
    }),
    scheduledEndAt: timestamp("scheduled_end_at", {
      withTimezone: true,
    }),

    meetingUrl: text("meeting_url"),
    rescheduleUrl: text("reschedule_url"),
    cancelUrl: text("cancel_url"),
    bookingMetadata: jsonb("booking_metadata").notNull().default({}),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    bookedAt: timestamp("booked_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    orderUnique: uniqueIndex("consultation_entitlements_order_unique")
      .on(table.orderId)
      .where(sql`${table.orderId} is not null`),
    bookingReferenceUnique: uniqueIndex(
      "consultation_entitlements_booking_reference_unique",
    )
      .on(table.bookingReference)
      .where(sql`${table.bookingReference} is not null`),
    userIdx: index("consultation_entitlements_user_idx").on(table.userId),
    statusIdx: index("consultation_entitlements_status_idx").on(table.status),
    scheduledStartIdx: index(
      "consultation_entitlements_scheduled_start_idx",
    ).on(table.scheduledStartAt),
  }),
);
