// @generated by install-humanet-values-marketing.mjs
import {
  index,
  jsonb,
  pgTable,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { users } from "./users";

export const consentRecords = pgTable(
  "consent_records",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    purpose: varchar("purpose", { length: 80 }).notNull(),
    // analytics | marketing_cookies | marketing_email
    version: varchar("version", { length: 80 }).notNull(),
    status: varchar("status", { length: 20 }).notNull(),
    // granted | withdrawn
    grantedAt: timestamp("granted_at", { withTimezone: true }),
    withdrawnAt: timestamp("withdrawn_at", { withTimezone: true }),
    source: varchar("source", { length: 80 }).notNull(),
    metadata: jsonb("metadata").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    userPurposeIdx: index("consent_records_user_purpose_idx").on(
      table.userId,
      table.purpose,
      table.createdAt,
    ),
  }),
);
