// @generated by install-humanet-values-marketing.mjs
import {
  boolean,
  index,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const legalDocuments = pgTable(
  "legal_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    type: varchar("type", { length: 40 }).notNull(),
    version: varchar("version", { length: 80 }).notNull(),
    contentHash: varchar("content_hash", { length: 128 }).notNull(),
    effectiveFrom: timestamp("effective_from", { withTimezone: true })
      .notNull()
      .defaultNow(),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    typeVersionUnique: uniqueIndex("legal_documents_type_version_unique").on(
      table.type,
      table.version,
    ),
    activeIdx: index("legal_documents_active_idx").on(
      table.type,
      table.isActive,
    ),
  }),
);
