// @generated by install-humanet-values-marketing.mjs
import {
  index,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

import { users } from "./users";
import { legalDocuments } from "./legal-documents";

export const legalAcceptances = pgTable(
  "legal_acceptances",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    documentId: uuid("document_id")
      .notNull()
      .references(() => legalDocuments.id, { onDelete: "restrict" }),
    acceptedAt: timestamp("accepted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    source: varchar("source", { length: 80 }).notNull(),
    ipHash: varchar("ip_hash", { length: 128 }),
    userAgentHash: varchar("user_agent_hash", { length: 128 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    userIdx: index("legal_acceptances_user_idx").on(table.userId),
    documentIdx: index("legal_acceptances_document_idx").on(table.documentId),
    uniqueAcceptance: uniqueIndex("legal_acceptances_user_document_unique").on(
      table.userId,
      table.documentId,
    ),
  }),
);
