// @generated by install-humanet-values-marketing.mjs
import {
  index,
  jsonb,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

import { users } from "./users";

export const purchaseIntents = pgTable(
  "purchase_intents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    offerCode: varchar("offer_code", { length: 80 }).notNull(),
    reportType: varchar("report_type", { length: 40 }).notNull(),
    productCode: varchar("product_code", { length: 120 }).notNull(),

    status: varchar("status", { length: 40 })
      .notNull()
      .default("created"),
    // created | questionnaire_started | questionnaire_completed |
    // checkout_started | paid | cancelled

    tenantSlug: varchar("tenant_slug", { length: 120 }),
    questionnaireVersionId: uuid("questionnaire_version_id"),
    projectQuestionnaireId: uuid("project_questionnaire_id"),
    assessmentSessionId: uuid("assessment_session_id"),
    orderId: uuid("order_id"),

    attribution: jsonb("attribution"),
    metadata: jsonb("metadata").notNull().default({}),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => ({
    userIdx: index("purchase_intents_user_idx").on(table.userId),
    sessionIdx: index("purchase_intents_session_idx").on(
      table.assessmentSessionId,
    ),
    orderIdx: index("purchase_intents_order_idx").on(table.orderId),
    statusIdx: index("purchase_intents_status_idx").on(table.status),
    oneIntentPerSessionOffer: uniqueIndex(
      "purchase_intents_session_offer_unique",
    )
      .on(table.userId, table.assessmentSessionId, table.offerCode)
      .where(sql`deleted_at is null and assessment_session_id is not null`),
  }),
);
