// @generated by install-humanet-values-marketing.mjs
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function Page() {
  redirect("/my/privacy");
}
