// @generated by install-humanet-values-marketing.mjs
import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { z } from "zod";

import { authOptions } from "@/auth";
import { appendConsentRecord } from "@/features/privacy/api/privacy-consent.mutations";

const schema = z.object({
  necessary: z.literal(true),
  analytics: z.boolean(),
  marketing: z.boolean(),
  version: z.string().trim().min(1).max(80),
  updatedAt: z.string().datetime(),
});

export async function POST(request: Request) {
  const parsed = schema.safeParse(await request.json().catch(() => null));

  if (!parsed.success) {
    return NextResponse.json({ ok: false }, { status: 400 });
  }

  const session = await getServerSession(authOptions);

  if (!session?.user?.id) {
    return NextResponse.json({ ok: true, persisted: false });
  }

  await Promise.all([
    appendConsentRecord({
      userId: session.user.id,
      purpose: "analytics",
      version: parsed.data.version,
      granted: parsed.data.analytics,
      source: "cookie_banner",
    }),
    appendConsentRecord({
      userId: session.user.id,
      purpose: "marketing_cookies",
      version: parsed.data.version,
      granted: parsed.data.marketing,
      source: "cookie_banner",
    }),
  ]);

  return NextResponse.json({ ok: true, persisted: true });
}
