// @generated by install-humanet-values-marketing.mjs
import type { AttributionSnapshot } from "@/features/attribution";
import {
  HUMANET_B2C_OFFER_CODES,
  type HumanetB2cOfferCode,
} from "@/shared/marketing/offer-codes";

export const OFFER_CODES = HUMANET_B2C_OFFER_CODES;
export const REPORT_TYPES = ["relations", "work", "change"] as const;

export type OfferCode = HumanetB2cOfferCode;
export type ReportType = (typeof REPORT_TYPES)[number];

export type PurchaseIntentStatus =
  | "created"
  | "questionnaire_started"
  | "questionnaire_completed"
  | "checkout_started"
  | "paid"
  | "cancelled";

export type PurchaseIntentInput = {
  offerCode: OfferCode;
  reportType: ReportType;
  productCode: string;
  tenantSlug: string;
  questionnaireVersionId: string;
  projectQuestionnaireId: string;
  assessmentSessionId: string;
  attribution: AttributionSnapshot | null;
};
