// @generated by install-humanet-values-marketing.mjs
export {
  ensureCurrentLegalDocuments,
  getCurrentLegalDocument,
  hasCurrentTermsAcceptance,
} from "./api/legal.queries";
export { recordCurrentTermsAcceptance } from "./api/legal.mutations";
