// @generated by install-humanet-values-marketing.mjs
"use client";

import { useEffect } from "react";

import { trackEvent } from "@/features/consent";

export function PurchaseAnalytics({
  orderId,
  currency,
  value,
  productCode,
  productName,
}: {
  orderId: string;
  currency: string;
  value: number;
  productCode: string;
  productName: string;
}) {
  useEffect(() => {
    const key = `humanet_purchase_event:${orderId}`;

    if (window.sessionStorage.getItem(key)) return;

    trackEvent("purchase", {
      ecommerce: {
        transaction_id: orderId,
        currency,
        value,
        items: [
          {
            item_id: productCode,
            item_name: productName,
            item_category: "report",
          },
        ],
      },
    });

    window.sessionStorage.setItem(key, "1");
  }, [currency, orderId, productCode, productName, value]);

  return null;
}
