// @generated by install-humanet-values-marketing.mjs
import { notFound } from "next/navigation";

import {
  getOwnedPurchaseIntent,
  PurchaseIntentCheckoutPage,
} from "@/features/purchase-flow";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function Page({
  params,
}: {
  params: Promise<{ purchaseIntentId: string }>;
}) {
  const { purchaseIntentId } = await params;
  const intent = await getOwnedPurchaseIntent(purchaseIntentId);

  if (!intent) notFound();

  return <PurchaseIntentCheckoutPage intent={intent} />;
}
