// @generated by install-humanet-values-marketing.mjs
"use client";

import Link from "next/link";

import { Button } from "@/components/ui/button";
import { useConsent } from "@/features/consent";
import {
  updateMarketingEmailConsentAction,
  withdrawResearchConsentAction,
} from "../api/privacy.actions";

type PrivacyState = {
  marketingEmail: { status: string } | null;
  research: {
    acceptedAt: Date;
    withdrawnAt: Date | null;
  } | null;
};

export function PrivacyPage({ state }: { state: PrivacyState }) {
  const { consent, saveConsent } = useConsent();
  const emailGranted = state.marketingEmail?.status === "granted";
  const researchActive = Boolean(state.research && !state.research.withdrawnAt);

  return (
    <main className="mx-auto w-full max-w-4xl space-y-6 px-4 py-8 sm:px-6">
      <div>
        <h1 className="text-3xl font-semibold">Prywatność i ustawienia</h1>
        <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">
          Tutaj możesz zdecydować, z których opcjonalnych funkcji korzystamy,
          oraz w każdej chwili zmienić swoje wybory.
        </p>
      </div>

      <Section title="Pliki cookie">
        <p className="text-sm leading-6 text-muted-foreground">
          Niezbędne pliki cookie są zawsze aktywne — odpowiadają m.in. za
          bezpieczne logowanie, płatności i zapamiętanie Twoich ustawień.
        </p>
        <Preference
          label="Analityczne"
          description="Pomagają nam zrozumieć, jak korzystasz z HUMANET, dzięki czemu możemy ulepszać serwis i przebieg badania."
          checked={consent.analytics}
          onChange={(analytics) =>
            saveConsent({ analytics, marketing: consent.marketing })
          }
        />
        <Preference
          label="Marketingowe"
          description="Pomagają mierzyć skuteczność naszych działań promocyjnych i lepiej dopasowywać komunikację. Możesz je wyłączyć w każdej chwili."
          checked={consent.marketing}
          onChange={(marketing) =>
            saveConsent({ analytics: consent.analytics, marketing })
          }
        />
        <Link
          href="/legal/polityka-prywatnosci"
          target="_blank"
          className="mt-4 inline-block text-sm font-medium underline underline-offset-4"
        >
          Zobacz Politykę prywatności
        </Link>
      </Section>

      <Section title="Informacje i oferty e-mail">
        <p className="text-sm text-muted-foreground">
          Ten wybór jest dobrowolny i nie wpływa na logowanie, badanie, zakup
          ani dostęp do raportu.
        </p>
        <form action={updateMarketingEmailConsentAction} className="mt-4">
          <input type="hidden" name="granted" value={emailGranted ? "false" : "true"} />
          <Button type="submit" variant={emailGranted ? "outline" : "default"}>
            {emailGranted ? "Wycofaj zgodę" : "Wyrażam zgodę"}
          </Button>
        </form>
      </Section>

      <Section title="Program badawczy i budowa norm">
        <p className="text-sm leading-6 text-muted-foreground">
          {researchActive
            ? "Twój udział jest aktywny. Możesz w każdej chwili wycofać zgodę na dalsze wykorzystanie danych w programie badawczym."
            : "Nie masz aktywnej zgody na udział w programie badawczym."}
        </p>
        {researchActive ? (
          <form action={withdrawResearchConsentAction} className="mt-4">
            <Button type="submit" variant="outline">
              Wycofaj zgodę badawczą
            </Button>
          </form>
        ) : null}
      </Section>

      <Section title="Dokumenty">
        <p className="text-sm leading-6 text-muted-foreground">
          Polityka prywatności wyjaśnia, jak przetwarzamy dane. Regulamin
          określa zasady korzystania z HUMANET VALUES i jest akceptowany przy
          składaniu zamówienia.
        </p>
        <div className="mt-4 flex flex-wrap gap-4 text-sm font-medium">
          <Link href="/legal/polityka-prywatnosci" target="_blank" className="underline underline-offset-4">
            Polityka prywatności
          </Link>
          <Link href="/legal/regulamin" target="_blank" className="underline underline-offset-4">
            Regulamin
          </Link>
        </div>
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border bg-white p-6 shadow-sm">
      <h2 className="text-xl font-semibold">{title}</h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function Preference({
  label,
  description,
  checked,
  onChange,
}: {
  label: string;
  description: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <label className="mt-3 flex items-start justify-between gap-5 rounded-xl border p-4">
      <span>
        <span className="block font-medium">{label}</span>
        <span className="mt-1 block text-xs leading-5 text-muted-foreground">
          {description}
        </span>
      </span>
      <input
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.currentTarget.checked)}
        className="mt-1 h-5 w-5 accent-teal-700"
      />
    </label>
  );
}
