// @generated by install-humanet-values-marketing.mjs
import {
  HUMANET_B2C_OFFER_CODES,
  type HumanetB2cOfferCode,
} from "@/shared/marketing/offer-codes";

export const REPORT_ACCESS_B2C_OFFER_CODES = HUMANET_B2C_OFFER_CODES;
export type ReportAccessB2cOfferCode = HumanetB2cOfferCode;

export type ReportAccessB2cConsultation = {
  kind: "report_consultation" | "decision_support";
  durationMinutes: number;
};

export type ReportAccessB2cOffer = {
  offerCode: ReportAccessB2cOfferCode;
  consultation: ReportAccessB2cConsultation | null;
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

export function isReportAccessB2cOfferCode(
  value: unknown,
): value is ReportAccessB2cOfferCode {
  return (
    typeof value === "string" &&
    REPORT_ACCESS_B2C_OFFER_CODES.includes(
      value as ReportAccessB2cOfferCode,
    )
  );
}

export function getReportAccessB2cOfferLabel(
  offerCode: ReportAccessB2cOfferCode,
): string {
  switch (offerCode) {
    case "report":
      return "Sam raport";
    case "report_plus_consultation":
      return "Raport + konsultacja";
    case "decision_support":
      return "Wsparcie decyzji";
  }
}

export function getDefaultConsultationMinutes(
  offerCode: ReportAccessB2cOfferCode,
): number | null {
  if (offerCode === "report_plus_consultation") return 60;
  if (offerCode === "decision_support") return 90;
  return null;
}

function normalizeMinutes(
  value: unknown,
  fallback: number,
): number {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return fallback;
  return Math.min(240, Math.max(15, Math.round(numeric)));
}

/**
 * Czyta zarówno pełny product.config ({ b2cOffer: ... }), jak i sam snapshot
 * b2cOffer zapisany w metadata zamówienia.
 */
export function readReportAccessB2cOffer(
  value: unknown,
): ReportAccessB2cOffer | null {
  const root = asRecord(value);
  const candidate =
    root.b2cOffer && typeof root.b2cOffer === "object"
      ? asRecord(root.b2cOffer)
      : root;

  const offerCode = candidate.offerCode;
  if (!isReportAccessB2cOfferCode(offerCode)) return null;

  if (offerCode === "report") {
    return { offerCode, consultation: null };
  }

  const consultation = asRecord(candidate.consultation);
  const defaultMinutes = getDefaultConsultationMinutes(offerCode) ?? 60;
  const durationMinutes = normalizeMinutes(
    consultation.durationMinutes,
    defaultMinutes,
  );

  return {
    offerCode,
    consultation: {
      kind:
        offerCode === "decision_support"
          ? "decision_support"
          : "report_consultation",
      durationMinutes,
    },
  };
}

export function mergeReportAccessB2cOfferConfig({
  currentConfig,
  offerCode,
  consultationMinutes,
}: {
  currentConfig: unknown;
  offerCode: ReportAccessB2cOfferCode | null;
  consultationMinutes?: unknown;
}): Record<string, unknown> {
  const next = { ...asRecord(currentConfig) };

  if (!offerCode) {
    delete next.b2cOffer;
    return next;
  }

  const defaultMinutes = getDefaultConsultationMinutes(offerCode);

  next.b2cOffer = {
    offerCode,
    consultation:
      defaultMinutes === null
        ? null
        : {
            kind:
              offerCode === "decision_support"
                ? "decision_support"
                : "report_consultation",
            durationMinutes: normalizeMinutes(
              consultationMinutes,
              defaultMinutes,
            ),
          },
  } satisfies ReportAccessB2cOffer;

  return next;
}
