// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";
import {
  CalendarCheck2,
  Clock3,
  FileText,
  Video,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { updateConsultationEntitlementAction } from "../api/consultation-admin.actions";
import { listConsultationEntitlementsAdmin } from "../api/consultation-admin.queries";
import { buildAdminConsultationReportHref } from "../lib/consultation-report-link";

function formatDateTime(value: Date | null) {
  if (!value) return "—";

  return new Intl.DateTimeFormat("pl-PL", {
    timeZone: "Europe/Warsaw",
    dateStyle: "medium",
    timeStyle: "short",
  }).format(value);
}

function kindLabel(kind: string) {
  switch (kind) {
    case "decision_support":
      return "Wsparcie w decyzji";
    case "report_consultation":
      return "Konsultacja raportu";
    case "standalone":
      return "Konsultacja dodatkowa";
    default:
      return kind;
  }
}

function statusLabel(status: string) {
  switch (status) {
    case "available":
      return "Do umówienia";
    case "booked":
      return "Umówiona";
    case "completed":
      return "Zrealizowana";
    case "expired":
      return "Wygasła";
    case "cancelled":
      return "Anulowana";
    case "no_show":
      return "Nie odbyła się";
    default:
      return status;
  }
}

export async function ConsultationsAdminPage() {
  const rows = await listConsultationEntitlementsAdmin();

  const bookedCount = rows.filter((row) => row.status === "booked").length;
  const availableCount = rows.filter(
    (row) => row.status === "available",
  ).length;
  const completedCount = rows.filter(
    (row) => row.status === "completed",
  ).length;

  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6">
      <section className="rounded-[2rem] hv-brand-card p-6 sm:p-8">
        <p className="hv-brand-eyebrow">HUMANET VALUES</p>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
          Konsultacje
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">
          Terminy i dane spotkań są synchronizowane z Cal.com. Przy
          konsultacji z raportem możesz od razu otworzyć raport użytkownika,
          a po otrzymaniu linku do wideospotkania – przejść do rozmowy.
        </p>

        <div className="mt-6 grid gap-3 sm:grid-cols-3">
          <Metric label="Umówione" value={bookedCount} />
          <Metric label="Do umówienia" value={availableCount} />
          <Metric label="Zrealizowane" value={completedCount} />
        </div>
      </section>

      <div className="mt-6 space-y-4">
        {rows.length === 0 ? (
          <div className="rounded-2xl border bg-white p-6 text-sm text-muted-foreground">
            Brak konsultacji.
          </div>
        ) : (
          rows.map((row) => {
            const reportHref =
              buildAdminConsultationReportHref(row.orderMetadata);

            return (
              <article
                key={row.id}
                className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6"
              >
                <div className="grid gap-5 xl:grid-cols-[1fr_auto]">
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="font-semibold">{row.userEmail}</p>
                      <span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-medium">
                        {statusLabel(row.status)}
                      </span>
                    </div>

                    <p className="mt-2 text-sm text-muted-foreground">
                      {kindLabel(row.kind)} · {row.durationMinutes} min
                      {row.source === "standalone"
                        ? " · konsultacja dodatkowa"
                        : " · pakiet B2C"}
                    </p>

                    <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm">
                      <span className="inline-flex items-center gap-2">
                        <CalendarCheck2 className="h-4 w-4 text-muted-foreground" />
                        {formatDateTime(row.scheduledStartAt)}
                      </span>
                      <span className="inline-flex items-center gap-2 text-muted-foreground">
                        <Clock3 className="h-4 w-4" />
                        {row.durationMinutes} min
                      </span>
                    </div>

                    <div className="mt-3 space-y-1 text-xs text-muted-foreground">
                      <p>
                        Referencja Cal.com:{" "}
                        <span className="font-mono text-foreground">
                          {row.bookingReference ?? "—"}
                        </span>
                      </p>
                      {row.orderId ? (
                        <p>
                          Zamówienie:{" "}
                          <span className="font-mono text-foreground">
                            {row.orderId}
                          </span>
                          {" · "}
                          płatność: {row.orderStatus ?? "—"}
                        </p>
                      ) : null}
                    </div>

                    <div className="mt-4 flex flex-wrap gap-2">
                      {row.meetingUrl ? (
                        <Button asChild className="rounded-full">
                          <a
                            href={row.meetingUrl}
                            target="_blank"
                            rel="noreferrer"
                          >
                            <Video className="h-4 w-4" />
                            {row.meetingUrl.includes("meet.google.com")
                              ? "Google Meet"
                              : "Dołącz do spotkania"}
                          </a>
                        </Button>
                      ) : null}

                      {reportHref ? (
                        <Button asChild variant="outline" className="rounded-full">
                          <Link href={reportHref} target="_blank">
                            <FileText className="h-4 w-4" />
                            Otwórz pełny raport
                          </Link>
                        </Button>
                      ) : null}
                    </div>
                  </div>

                  <form
                    action={updateConsultationEntitlementAction}
                    className="flex flex-wrap items-end gap-2 xl:justify-end"
                  >
                    <input
                      type="hidden"
                      name="entitlementId"
                      value={row.id}
                    />
                    <label className="text-xs">
                      <span className="mb-1 block">Status</span>
                      <select
                        name="status"
                        defaultValue={row.status}
                        className="h-10 rounded-md border bg-white px-3 text-sm"
                      >
                        <option value="available">Do umówienia</option>
                        <option value="booked">Umówiona</option>
                        <option value="completed">Zrealizowana</option>
                        <option value="expired">Wygasła</option>
                        <option value="cancelled">Anulowana</option>
                        <option value="no_show">Nie odbyła się</option>
                      </select>
                    </label>

                    <label className="text-xs">
                      <span className="mb-1 block">Referencja Cal.com</span>
                      <Input
                        name="bookingReference"
                        defaultValue={row.bookingReference ?? ""}
                        className="w-56"
                      />
                    </label>

                    <Button type="submit">Zapisz</Button>
                  </form>
                </div>
              </article>
            );
          })
        )}
      </div>
    </main>
  );
}

function Metric({
  label,
  value,
}: {
  label: string;
  value: number;
}) {
  return (
    <div className="rounded-2xl border bg-white/70 p-4">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
        {label}
      </p>
      <p className="mt-2 text-3xl font-semibold">{value}</p>
    </div>
  );
}
