// @generated by install-humanet-values-marketing.mjs
export const HUMANET_CONSENT_COOKIE_NAME = "humanet_consent_v1";
export const HUMANET_CONSENT_EVENT_NAME = "humanet:consent-changed";
export const HUMANET_CONSENT_MAX_AGE_SECONDS = 60 * 60 * 24 * 180;

export type ConsentState = {
  necessary: true;
  analytics: boolean;
  marketing: boolean;
  version: string;
  updatedAt: string;
};

export function createDefaultConsentState(version: string): ConsentState {
  return {
    necessary: true,
    analytics: false,
    marketing: false,
    version,
    updatedAt: new Date().toISOString(),
  };
}
