// @generated by install-humanet-values-marketing.mjs
import "server-only";

export const CURRENT_LEGAL_DOCUMENTS = [
  {
    type: "terms" as const,
    version: process.env.LEGAL_TERMS_VERSION?.trim() || "2026-08-01",
    contentHash: "f7a80d2049372596e68837679630571b76517bf47d2bb597ac856953fe70c1c1",
    href: "/legal/regulamin",
    label: "Regulamin korzystania z HUMANET VALUES",
  },
  {
    type: "privacy_notice" as const,
    version: process.env.LEGAL_PRIVACY_VERSION?.trim() || "2026-08-01",
    contentHash: "9a9e4870fcef6e353ec28e3df503d6eddb88097eef1fdbeaaa5219ad67505689",
    href: "/legal/polityka-prywatnosci",
    label: "Polityka prywatności",
  },
] as const;
