// @generated by install-humanet-values-marketing.mjs
import crypto from "node:crypto";

import { and, eq, isNull, sql } from "drizzle-orm";
import { NextResponse } from "next/server";

import {
  consultationEntitlements,
  users,
} from "@/drizzle/schema";
import { controlDb } from "@/server/db/control-db";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function normalizeString(value: unknown): string | null {
  return typeof value === "string" && value.trim()
    ? value.trim()
    : null;
}

function normalizeEmail(value: unknown): string | null {
  const email = normalizeString(value)?.toLowerCase();
  return email || null;
}

function safeDate(value: unknown): Date | null {
  const raw = normalizeString(value);
  if (!raw) return null;

  const date = new Date(raw);
  return Number.isNaN(date.getTime()) ? null : date;
}

function findValueByKeys(
  value: unknown,
  keys: Set<string>,
  depth = 0,
): unknown {
  if (depth > 7 || value == null) return null;

  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findValueByKeys(item, keys, depth + 1);
      if (found != null) return found;
    }
    return null;
  }

  if (!isRecord(value)) return null;

  for (const [key, candidate] of Object.entries(value)) {
    if (keys.has(key) && candidate != null) {
      return candidate;
    }
  }

  for (const candidate of Object.values(value)) {
    const found = findValueByKeys(candidate, keys, depth + 1);
    if (found != null) return found;
  }

  return null;
}

function findStringByKeys(
  value: unknown,
  keys: string[],
): string | null {
  return normalizeString(
    findValueByKeys(value, new Set(keys)),
  );
}

function findAttendeeEmail(value: unknown): string | null {
  if (!isRecord(value)) return null;

  const attendeeContainers = [
    value.attendees,
    value.attendee,
    value.booker,
    value.responses,
  ];

  for (const container of attendeeContainers) {
    const email = normalizeEmail(
      findValueByKeys(container, new Set(["email"]), 0),
    );
    if (email) return email;
  }

  if (isRecord(value.payload)) {
    return findAttendeeEmail(value.payload);
  }

  return null;
}

function findMeetingUrl(value: unknown, depth = 0): string | null {
  if (depth > 8 || value == null) return null;

  if (typeof value === "string") {
    const candidate = value.trim();

    if (
      /^https:\/\//i.test(candidate) &&
      (
        candidate.includes("meet.google.com") ||
        candidate.includes("zoom.us") ||
        candidate.includes("teams.microsoft.com") ||
        candidate.includes("cal.com/video") ||
        candidate.includes("cal.video")
      )
    ) {
      return candidate;
    }

    return null;
  }

  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findMeetingUrl(item, depth + 1);
      if (found) return found;
    }
    return null;
  }

  if (!isRecord(value)) return null;

  for (const key of [
    "meetingUrl",
    "videoCallUrl",
    "videoCallURL",
    "conferenceUrl",
    "conferenceURL",
    "location",
  ]) {
    const found = findMeetingUrl(value[key], depth + 1);
    if (found) return found;
  }

  for (const candidate of Object.values(value)) {
    const found = findMeetingUrl(candidate, depth + 1);
    if (found) return found;
  }

  return null;
}

function verifySignature(rawBody: string, signatureHeader: string | null) {
  const secret = process.env.CALCOM_WEBHOOK_SECRET?.trim();

  if (!secret) {
    throw new Error("Missing CALCOM_WEBHOOK_SECRET.");
  }

  if (!signatureHeader) return false;

  const received = signatureHeader
    .trim()
    .replace(/^sha256=/i, "")
    .toLowerCase();

  const expected = crypto
    .createHmac("sha256", secret)
    .update(rawBody)
    .digest("hex");

  const receivedBuffer = Buffer.from(received);
  const expectedBuffer = Buffer.from(expected);

  return (
    receivedBuffer.length === expectedBuffer.length &&
    crypto.timingSafeEqual(receivedBuffer, expectedBuffer)
  );
}

function eventStatus(trigger: string | null) {
  switch (trigger) {
    case "BOOKING_CREATED":
    case "BOOKING_CONFIRMED":
    case "BOOKING_RESCHEDULED":
    case "BOOKING_REOPENED":
      return "booked";
    case "BOOKING_COMPLETED":
      return "completed";
    case "BOOKING_CANCELLED":
    case "BOOKING_REJECTED":
      return "cancelled";
    case "BOOKING_NO_SHOW":
    case "BOOKING_NO_SHOW_UPDATED":
      return "no_show";
    default:
      return null;
  }
}

function durationMinutes(start: Date | null, end: Date | null) {
  if (!start || !end) return 60;

  const minutes = Math.round(
    (end.getTime() - start.getTime()) / 60_000,
  );

  return Number.isFinite(minutes) && minutes > 0
    ? Math.min(480, minutes)
    : 60;
}

async function findExistingEntitlement({
  entitlementId,
  orderId,
  bookingReference,
}: {
  entitlementId: string | null;
  orderId: string | null;
  bookingReference: string | null;
}) {
  if (entitlementId) {
    const row =
      await controlDb.query.consultationEntitlements.findFirst({
        where: eq(consultationEntitlements.id, entitlementId),
      });
    if (row) return row;
  }

  if (orderId) {
    const row =
      await controlDb.query.consultationEntitlements.findFirst({
        where: eq(consultationEntitlements.orderId, orderId),
      });
    if (row) return row;
  }

  if (bookingReference) {
    const row =
      await controlDb.query.consultationEntitlements.findFirst({
        where: eq(
          consultationEntitlements.bookingReference,
          bookingReference,
        ),
      });
    if (row) return row;
  }

  return null;
}

async function userByEmail(email: string) {
  const rows = await controlDb
    .select({
      id: users.id,
      email: users.email,
    })
    .from(users)
    .where(
      and(
        sql`lower(${users.email}) = ${email}`,
        eq(users.status, "active"),
        isNull(users.deletedAt),
      ),
    )
    .limit(1);

  return rows[0] ?? null;
}

export async function POST(request: Request) {
  const rawBody = await request.text();

  try {
    if (
      !verifySignature(
        rawBody,
        request.headers.get("x-cal-signature-256"),
      )
    ) {
      return NextResponse.json(
        { ok: false, error: "invalid_signature" },
        { status: 401 },
      );
    }
  } catch (error) {
    console.error("CALCOM_WEBHOOK_CONFIGURATION_ERROR", {
      errorName:
        error instanceof Error ? error.name : "UnknownError",
    });

    return NextResponse.json(
      { ok: false, error: "webhook_not_configured" },
      { status: 503 },
    );
  }

  let body: unknown;

  try {
    body = JSON.parse(rawBody) as unknown;
  } catch {
    return NextResponse.json(
      { ok: false, error: "invalid_json" },
      { status: 400 },
    );
  }

  const trigger =
    findStringByKeys(body, [
      "triggerEvent",
      "trigger",
      "eventTrigger",
      "type",
    ])?.toUpperCase() ?? null;

  const status = eventStatus(trigger);

  if (!status) {
    return NextResponse.json({
      ok: true,
      handled: false,
      reason: "unsupported_trigger",
      trigger,
    });
  }

  const entitlementId = findStringByKeys(body, [
    "consultationEntitlementId",
    "entitlementId",
  ]);
  const orderId = findStringByKeys(body, [
    "orderId",
    "humanetOrderId",
  ]);
  const bookingReference = findStringByKeys(body, [
    "uid",
    "bookingUid",
    "bookingUID",
    "bookingId",
    "bookingReference",
  ]);

  const start =
    safeDate(
      findValueByKeys(
        body,
        new Set(["startTime", "start", "startsAt"]),
      ),
    ) ?? null;

  const end =
    safeDate(
      findValueByKeys(
        body,
        new Set(["endTime", "end", "endsAt"]),
      ),
    ) ?? null;

  const attendeeEmail = findAttendeeEmail(body);
  const meetingUrl = findMeetingUrl(body);
  const rescheduleUrl = findStringByKeys(body, [
    "rescheduleUrl",
    "rescheduleURL",
  ]);
  const cancelUrl = findStringByKeys(body, [
    "cancelUrl",
    "cancelURL",
    "cancellationUrl",
  ]);

  const existing = await findExistingEntitlement({
    entitlementId,
    orderId,
    bookingReference,
  });

  const now = new Date();

  if (existing) {
    if (attendeeEmail) {
      const owner = await controlDb.query.users.findFirst({
        where: eq(users.id, existing.userId),
        columns: { email: true },
      });

      if (
        owner?.email &&
        owner.email.trim().toLowerCase() !== attendeeEmail
      ) {
        return NextResponse.json(
          { ok: false, error: "attendee_mismatch" },
          { status: 409 },
        );
      }
    }

    const restoredPackageAvailability =
      status === "cancelled" &&
      existing.source === "package";

    await controlDb
      .update(consultationEntitlements)
      .set({
        status: restoredPackageAvailability
          ? "available"
          : status,
        bookingReference:
          bookingReference ?? existing.bookingReference,
        scheduledStartAt: restoredPackageAvailability
          ? null
          : start ?? existing.scheduledStartAt,
        scheduledEndAt: restoredPackageAvailability
          ? null
          : end ?? existing.scheduledEndAt,
        meetingUrl: restoredPackageAvailability
          ? null
          : meetingUrl ?? existing.meetingUrl,
        rescheduleUrl: restoredPackageAvailability
          ? null
          : rescheduleUrl ?? existing.rescheduleUrl,
        cancelUrl: restoredPackageAvailability
          ? null
          : cancelUrl ?? existing.cancelUrl,
        bookedAt:
          status === "booked"
            ? existing.bookedAt ?? now
            : existing.bookedAt,
        completedAt:
          status === "completed"
            ? existing.completedAt ?? now
            : existing.completedAt,
        cancelledAt:
          status === "cancelled"
            ? now
            : existing.cancelledAt,
        bookingMetadata: {
          trigger,
          attendeeEmail,
          synchronizedAt: now.toISOString(),
        },
        updatedAt: now,
      })
      .where(eq(consultationEntitlements.id, existing.id));

    return NextResponse.json({
      ok: true,
      handled: true,
      mode: "updated",
      entitlementId: existing.id,
    });
  }

  if (!attendeeEmail || !bookingReference) {
    return NextResponse.json({
      ok: true,
      handled: false,
      reason: "no_matching_entitlement",
    });
  }

  const owner = await userByEmail(attendeeEmail);

  if (!owner) {
    return NextResponse.json({
      ok: true,
      handled: false,
      reason: "user_not_found",
    });
  }

  const [created] = await controlDb
    .insert(consultationEntitlements)
    .values({
      orderId: null,
      userId: owner.id,
      source: "standalone",
      kind: "standalone",
      durationMinutes: durationMinutes(start, end),
      status,
      bookingProvider: "calcom",
      bookingReference,
      scheduledStartAt: start,
      scheduledEndAt: end,
      meetingUrl,
      rescheduleUrl,
      cancelUrl,
      bookedAt: status === "booked" ? now : null,
      completedAt: status === "completed" ? now : null,
      cancelledAt: status === "cancelled" ? now : null,
      bookingMetadata: {
        trigger,
        attendeeEmail,
        synchronizedAt: now.toISOString(),
      },
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoNothing()
    .returning({ id: consultationEntitlements.id });

  return NextResponse.json({
    ok: true,
    handled: Boolean(created),
    mode: created ? "created_standalone" : "duplicate",
    entitlementId: created?.id ?? null,
  });
}
