// @generated by install-humanet-values-consultations-v5.mjs
import crypto from "node:crypto";

import { and, desc, eq, isNull, sql } from "drizzle-orm";
import { NextResponse } from "next/server";

import { consultationEntitlements, users } from "@/drizzle/schema";
import { controlDb } from "@/server/db/control-db";
import { chooseConsultationEntitlementForBooking } from "@/features/purchase-flow/lib/consultation-booking-match";
import { getConfiguredCalComEventSlugs } from "@/features/purchase-flow/lib/calcom-config.server";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function record(value: unknown): Record<string, unknown> {
  return isRecord(value) ? value : {};
}

function text(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function email(value: unknown): string | null {
  return text(value)?.toLowerCase() ?? null;
}

function safeDate(value: unknown): Date | null {
  const raw = text(value);
  if (!raw) return null;
  const result = new Date(raw);
  return Number.isNaN(result.getTime()) ? null : result;
}

function verifySignature(rawBody: string, signatureHeader: string | null) {
  const secret = process.env.CALCOM_WEBHOOK_SECRET?.trim();
  if (!secret) throw new Error("Missing CALCOM_WEBHOOK_SECRET.");
  if (!signatureHeader) return false;

  const received = signatureHeader.trim().replace(/^sha256=/i, "").toLowerCase();
  const expected = crypto.createHmac("sha256", secret).update(rawBody).digest("hex");
  const receivedBuffer = Buffer.from(received);
  const expectedBuffer = Buffer.from(expected);

  return (
    receivedBuffer.length === expectedBuffer.length &&
    crypto.timingSafeEqual(receivedBuffer, expectedBuffer)
  );
}

function attendeeEmail(payload: Record<string, unknown>): string | null {
  const attendees = Array.isArray(payload.attendees) ? payload.attendees : [];
  for (const item of attendees) {
    const result = email(record(item).email);
    if (result) return result;
  }

  const responses = record(payload.responses);
  const responseEmail = record(responses.email);
  return email(responseEmail.value);
}

function meetingUrl(payload: Record<string, unknown>): string | null {
  const metadata = record(payload.metadata);
  const videoCallData = record(payload.videoCallData);

  for (const candidate of [
    metadata.videoCallUrl,
    videoCallData.url,
    payload.meetingUrl,
    payload.location,
  ]) {
    const value = text(candidate);
    if (value?.startsWith("https://")) return value;
  }

  return null;
}

function eventStatus(trigger: string) {
  if (["BOOKING_CREATED", "BOOKING_CONFIRMED", "BOOKING_RESCHEDULED", "BOOKING_REOPENED"].includes(trigger)) {
    return "booked" as const;
  }
  if (trigger === "BOOKING_COMPLETED" || trigger === "MEETING_ENDED") {
    return "completed" as const;
  }
  if (trigger === "BOOKING_CANCELLED" || trigger === "BOOKING_REJECTED") {
    return "cancelled" as const;
  }
  if (trigger === "BOOKING_NO_SHOW" || trigger === "BOOKING_NO_SHOW_UPDATED") {
    return "no_show" as const;
  }
  return null;
}

async function userByEmail(normalizedEmail: string) {
  const rows = await controlDb
    .select({ id: users.id, email: users.email })
    .from(users)
    .where(
      and(
        sql`lower(${users.email}) = ${normalizedEmail}`,
        eq(users.status, "active"),
        isNull(users.deletedAt),
      ),
    )
    .limit(1);
  return rows[0] ?? null;
}

function hintsForEvent(payload: Record<string, unknown>) {
  const slug = text(payload.type);
  const configured = getConfiguredCalComEventSlugs();

  if (slug && configured.decision === slug) {
    return { kindHint: "decision_support" as const, sourceHint: "package" as const };
  }

  if (slug && configured.standalone === slug && configured.standalone !== configured.report) {
    return { kindHint: "standalone" as const, sourceHint: "standalone" as const };
  }

  if (slug && configured.report === slug && configured.standalone !== configured.report) {
    return { kindHint: "report_consultation" as const, sourceHint: "package" as const };
  }

  return { kindHint: null, sourceHint: null };
}

export async function POST(request: Request) {
  const rawBody = await request.text();

  try {
    if (!verifySignature(rawBody, request.headers.get("x-cal-signature-256"))) {
      return NextResponse.json({ ok: false, error: "invalid_signature" }, { status: 401 });
    }
  } catch (error) {
    console.error("CALCOM_WEBHOOK_CONFIGURATION_ERROR", {
      errorName: error instanceof Error ? error.name : "UnknownError",
    });
    return NextResponse.json({ ok: false, error: "webhook_not_configured" }, { status: 503 });
  }

  let body: Record<string, unknown>;
  try {
    body = record(JSON.parse(rawBody));
  } catch {
    return NextResponse.json({ ok: false, error: "invalid_json" }, { status: 400 });
  }

  const trigger = text(body.triggerEvent)?.toUpperCase() ?? "";
  const status = eventStatus(trigger);
  if (!status) {
    return NextResponse.json({ ok: true, handled: false, reason: "unsupported_trigger", trigger });
  }

  const payload = isRecord(body.payload) ? record(body.payload) : body;
  const metadata = record(payload.metadata);

  const entitlementId =
    text(metadata.consultationEntitlementId) ?? text(metadata.entitlementId);
  const orderId = text(metadata.orderId) ?? text(metadata.humanetOrderId);
  const source = text(metadata.source);
  const bookingReference = text(payload.uid) ?? text(payload.bookingUid);
  const previousBookingReference = text(payload.rescheduleUid);
  const attendee = attendeeEmail(payload);
  const start = safeDate(payload.startTime ?? payload.start);
  const end = safeDate(payload.endTime ?? payload.end);
  const meeting = meetingUrl(payload);
  const rawLength = Number(payload.length);
  const lengthMinutes = Number.isFinite(rawLength) && rawLength > 0
    ? rawLength
    : start && end
      ? Math.round((end.getTime() - start.getTime()) / 60_000)
      : null;

  let existing = entitlementId
    ? await controlDb.query.consultationEntitlements.findFirst({
        where: eq(consultationEntitlements.id, entitlementId),
      })
    : null;

  if (!existing && orderId) {
    existing = await controlDb.query.consultationEntitlements.findFirst({
      where: eq(consultationEntitlements.orderId, orderId),
    });
  }

  if (!existing && previousBookingReference) {
    existing = await controlDb.query.consultationEntitlements.findFirst({
      where: eq(consultationEntitlements.bookingReference, previousBookingReference),
    });
  }

  if (!existing && bookingReference) {
    existing = await controlDb.query.consultationEntitlements.findFirst({
      where: eq(consultationEntitlements.bookingReference, bookingReference),
    });
  }

  let owner = attendee ? await userByEmail(attendee) : null;

  if (!existing && owner && bookingReference) {
    const candidates = await controlDb
      .select()
      .from(consultationEntitlements)
      .where(eq(consultationEntitlements.userId, owner.id))
      .orderBy(desc(consultationEntitlements.updatedAt));
    const hints = hintsForEvent(payload);
    const selected = chooseConsultationEntitlementForBooking(
      candidates.map((candidate) => ({
        id: candidate.id,
        source: candidate.source,
        kind: candidate.kind,
        durationMinutes: candidate.durationMinutes,
        status: candidate.status,
        bookingReference: candidate.bookingReference,
        createdAt: candidate.createdAt,
        bookingMetadata: candidate.bookingMetadata,
      })),
      {
        uid: bookingReference,
        durationMinutes: lengthMinutes,
        createdAt: safeDate(body.createdAt),
        sourceHint:
          source === "standalone"
            ? "standalone"
            : source === "package"
              ? "package"
              : hints.sourceHint,
        kindHint: hints.kindHint,
      },
    );
    existing = selected
      ? candidates.find((candidate) => candidate.id === selected.id) ?? null
      : null;
  }

  if (!existing && owner && bookingReference && source === "standalone") {
    const now = new Date();
    const [created] = await controlDb
      .insert(consultationEntitlements)
      .values({
        orderId: null,
        userId: owner.id,
        source: "standalone",
        kind: "standalone",
        durationMinutes: lengthMinutes && lengthMinutes > 0 ? lengthMinutes : 60,
        status: "available",
        bookingProvider: "calcom",
        bookingMetadata: { recoveredFromWebhook: true },
        createdAt: now,
        updatedAt: now,
      })
      .returning();
    existing = created;
  }

  if (!existing || !bookingReference) {
    console.warn("CALCOM_WEBHOOK_UNMATCHED_BOOKING", {
      trigger,
      attendee,
      bookingReference,
      hasEntitlementMetadata: Boolean(entitlementId),
      hasOrderMetadata: Boolean(orderId),
    });
    return NextResponse.json({ ok: true, handled: false, reason: "no_matching_entitlement" });
  }

  if (!owner) {
    const userRow = await controlDb.query.users.findFirst({
      where: eq(users.id, existing.userId),
      columns: { id: true, email: true },
    });
    owner = userRow ?? null;
  }

  if (attendee && owner?.email && owner.email.toLowerCase() !== attendee) {
    return NextResponse.json({ ok: false, error: "attendee_mismatch" }, { status: 409 });
  }

  const now = new Date();
  const restorePackage = status === "cancelled" && existing.source === "package";

  await controlDb
    .update(consultationEntitlements)
    .set({
      status: restorePackage ? "available" : status,
      bookingReference,
      scheduledStartAt: restorePackage ? null : start ?? existing.scheduledStartAt,
      scheduledEndAt: restorePackage ? null : end ?? existing.scheduledEndAt,
      meetingUrl: restorePackage ? null : meeting ?? existing.meetingUrl,
      durationMinutes:
        lengthMinutes && lengthMinutes > 0
          ? Math.min(480, lengthMinutes)
          : existing.durationMinutes,
      bookedAt: status === "booked" ? existing.bookedAt ?? now : existing.bookedAt,
      completedAt: status === "completed" ? existing.completedAt ?? now : existing.completedAt,
      cancelledAt: status === "cancelled" ? now : null,
      bookingMetadata: {
        ...record(existing.bookingMetadata),
        ...metadata,
        trigger,
        attendeeEmail: attendee,
        webhookVersion: request.headers.get("x-cal-webhook-version"),
        synchronizedAt: now.toISOString(),
      },
      updatedAt: now,
    })
    .where(eq(consultationEntitlements.id, existing.id));

  return NextResponse.json({
    ok: true,
    handled: true,
    entitlementId: existing.id,
    trigger,
  });
}
