// @generated by install-humanet-values-marketing.mjs
import { z } from "zod";

import {
  OFFER_CODES,
  REPORT_TYPES,
} from "../types/purchase-flow.types";

export const offerCodeSchema = z.enum(OFFER_CODES);
export const reportTypeSchema = z.enum(REPORT_TYPES);

export const startFlowSearchParamsSchema = z.object({
  offer: offerCodeSchema.optional(),
  reportType: reportTypeSchema.optional(),
  utm_source: z.string().trim().max(255).optional(),
  utm_medium: z.string().trim().max(255).optional(),
  utm_campaign: z.string().trim().max(255).optional(),
  utm_content: z.string().trim().max(255).optional(),
  utm_term: z.string().trim().max(255).optional(),
  ref: z.string().trim().max(255).optional(),
  partner: z.string().trim().max(255).optional(),
});

export function safeInternalCallback(
  value: string | null | undefined,
  fallback = "/my/assessment",
): string {
  if (!value || !value.startsWith("/") || value.startsWith("//")) {
    return fallback;
  }

  try {
    const url = new URL(value, "https://values.humanet.me");
    if (url.origin !== "https://values.humanet.me") return fallback;
    return `${url.pathname}${url.search}${url.hash}`;
  } catch {
    return fallback;
  }
}
