// @generated by install-humanet-values-marketing.mjs
import { describe, expect, it } from "vitest";

import {
  safeInternalCallback,
  startFlowSearchParamsSchema,
} from "./start-flow.schema";

describe("start flow input", () => {
  it("accepts known offer and report type", () => {
    const result = startFlowSearchParamsSchema.safeParse({
      offer: "report",
      reportType: "work",
    });

    expect(result.success).toBe(true);
  });

  it("rejects unknown offer", () => {
    const result = startFlowSearchParamsSchema.safeParse({
      offer: "price-from-url",
    });

    expect(result.success).toBe(false);
  });

  it("blocks external callback", () => {
    expect(safeInternalCallback("https://evil.example/x")).toBe(
      "/my/assessment",
    );
    expect(safeInternalCallback("//evil.example/x")).toBe(
      "/my/assessment",
    );
  });
});
