// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { CURRENT_LEGAL_DOCUMENTS } from "../config/legal-documents.config";
import { acceptCurrentLegalDocumentsAction } from "../api/legal.actions";

export function LegalAcceptancePage({
  callbackUrl,
}: {
  callbackUrl: string;
}) {
  return (
    <main className="min-h-screen hv-brand-surface px-4 py-10 sm:px-6">
      <form
        action={acceptCurrentLegalDocumentsAction}
        className="mx-auto max-w-2xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8"
      >
        <p className="hv-brand-eyebrow">HUMANET VALUES</p>
        <h1 className="mt-3 text-3xl font-semibold">
          Dokumenty wymagane do korzystania z usługi
        </h1>
        <p className="mt-4 text-sm leading-7 text-muted-foreground">
          Akceptacja dokumentów jest odrębna od dobrowolnych zgód na analitykę,
          marketing i udział w badaniach.
        </p>

        <input type="hidden" name="callbackUrl" value={callbackUrl} />

        <label className="mt-6 flex gap-3 rounded-xl border p-4">
          <input
            type="checkbox"
            name="acceptTerms"
            required
            className="mt-1 h-5 w-5 accent-teal-700"
          />
          <span className="text-sm leading-6">
            Akceptuję{" "}
            <Link
              href={CURRENT_LEGAL_DOCUMENTS[0].href}
              target="_blank"
              className="font-semibold underline"
            >
              Regulamin korzystania z HUMANET VALUES
            </Link>
            .
          </span>
        </label>

        <label className="mt-3 flex gap-3 rounded-xl border p-4">
          <input
            type="checkbox"
            name="acceptPrivacy"
            required
            className="mt-1 h-5 w-5 accent-teal-700"
          />
          <span className="text-sm leading-6">
            Potwierdzam, że zapoznałem/am się z{" "}
            <Link
              href={CURRENT_LEGAL_DOCUMENTS[1].href}
              target="_blank"
              className="font-semibold underline"
            >
              Polityką prywatności
            </Link>
            .
          </span>
        </label>

        <Button type="submit" className="mt-6 rounded-full">
          Zapisz akceptacje i przejdź dalej
        </Button>
      </form>
    </main>
  );
}
