// @generated by install-humanet-values-consultations-v5.mjs
"use client";

import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import { useRouter } from "next/navigation";

import { trackEvent } from "@/features/consent";

type CalApi = ((...args: unknown[]) => void) & {
  q?: ArrayLike<unknown>[];
  loaded?: boolean;
  ns?: Record<string, CalApi>;
};

declare global {
  interface Window {
    Cal?: CalApi;
    __humanetCalReady?: Promise<void>;
  }
}

function createQueuedApi(push: (api: CalApi, args: ArrayLike<unknown>) => void): CalApi {
  const api = function () {
    push(api, arguments);
  } as CalApi;
  api.q = [];
  return api;
}

function ensureCalBootstrap(): CalApi {
  if (window.Cal) return window.Cal;

  const push = (api: CalApi, args: ArrayLike<unknown>) => {
    api.q = api.q ?? [];
    api.q.push(args);
  };

  const cal = function () {
    const api = window.Cal as CalApi;
    const args = arguments;

    if (!api.loaded) {
      api.ns = api.ns ?? {};
      api.q = api.q ?? [];

      const script = document.createElement("script");
      script.src = "https://app.cal.com/embed/embed.js";
      script.async = true;
      window.__humanetCalReady = new Promise<void>((resolve, reject) => {
        script.addEventListener("load", () => resolve(), { once: true });
        script.addEventListener(
          "error",
          () => reject(new Error("Nie udało się załadować Cal.com.")),
          { once: true },
        );
      });
      document.head.appendChild(script);
      api.loaded = true;
    }

    if (args[0] === "init") {
      const namespace = args[1];
      if (typeof namespace === "string") {
        api.ns = api.ns ?? {};
        const namespaceApi = api.ns[namespace] ?? createQueuedApi(push);
        api.ns[namespace] = namespaceApi;
        push(namespaceApi, args);
        push(api, ["initNamespace", namespace]);
        return;
      }
    }

    push(api, args);
  } as CalApi;

  cal.q = [];
  cal.ns = {};
  window.Cal = cal;
  return cal;
}

function parseCalTarget(href: string) {
  const url = new URL(href);
  return {
    origin: url.origin,
    calLink: url.pathname.replace(/^\/+|\/+$/g, ""),
  };
}

function eventData(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  const detail = (value as Record<string, unknown>).detail;
  if (!detail || typeof detail !== "object" || Array.isArray(detail)) return {};
  const data = (detail as Record<string, unknown>).data;
  return data && typeof data === "object" && !Array.isArray(data)
    ? (data as Record<string, unknown>)
    : {};
}

export function CalBookingButton({
  href,
  entitlementId,
  orderId,
  durationMinutes,
  source,
  surface,
  userEmail = null,
  userName = null,
  children,
  className,
  autoOpen = false,
  returnTo = null,
}: {
  href: string;
  entitlementId: string;
  orderId: string | null;
  durationMinutes: number;
  source: "package" | "standalone";
  surface: string;
  userEmail?: string | null;
  userName?: string | null;
  children?: ReactNode;
  className?: string;
  autoOpen?: boolean;
  returnTo?: string | null;
}) {
  const router = useRouter();
  const buttonRef = useRef<HTMLButtonElement>(null);
  const autoOpened = useRef(false);
  const processedUid = useRef<string | null>(null);
  const [ready, setReady] = useState(false);

  const target = useMemo(() => parseCalTarget(href), [href]);
  const namespace = useMemo(
    () => `humanet-${entitlementId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 16)}`,
    [entitlementId],
  );

  const config = useMemo(() => {
    const value: Record<string, string> = {
      layout: "month_view",
      "metadata[consultationEntitlementId]": entitlementId,
      "metadata[source]": source,
    };

    if (orderId) value["metadata[orderId]"] = orderId;
    if (userEmail) value.email = userEmail;
    if (userName) value.name = userName;

    return value;
  }, [entitlementId, orderId, source, userEmail, userName]);

  useEffect(() => {
    const cal = ensureCalBootstrap();
    cal("init", namespace, { origin: target.origin });
    const namespaceApi = cal.ns?.[namespace];

    if (!namespaceApi) return;

    const handleSuccessfulBooking = async (event: unknown) => {
      const data = eventData(event);
      const uid = typeof data.uid === "string" ? data.uid : null;
      const startTime =
        typeof data.startTime === "string" ? data.startTime : null;
      const endTime = typeof data.endTime === "string" ? data.endTime : null;

      if (!uid || !startTime || !endTime || processedUid.current === uid) {
        return;
      }

      processedUid.current = uid;

      const response = await fetch("/api/consultations/booking-completed", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          entitlementId,
          uid,
          startTime,
          endTime,
          videoCallUrl:
            typeof data.videoCallUrl === "string" ? data.videoCallUrl : null,
          eventTypeId:
            typeof data.eventTypeId === "number" ? data.eventTypeId : null,
          status: typeof data.status === "string" ? data.status : null,
        }),
      });

      if (!response.ok) {
        processedUid.current = null;
        return;
      }

      trackEvent("consultation_booked", {
        consultation_minutes: durationMinutes,
        surface,
      });

      namespaceApi("closeModal");
      router.refresh();
      if (returnTo) router.push(returnTo);
    };

    namespaceApi("on", {
      action: "bookingSuccessfulV2",
      callback: handleSuccessfulBooking,
    });
    namespaceApi("on", {
      action: "rescheduleBookingSuccessfulV2",
      callback: handleSuccessfulBooking,
    });
    namespaceApi("preload", { calLink: target.calLink });
    namespaceApi("ui", {
      hideEventTypeDetails: false,
      layout: "month_view",
    });

    const readyPromise = window.__humanetCalReady ?? Promise.resolve();
    readyPromise
      .then(() => setReady(true))
      .catch(() => setReady(false));
  }, [
    durationMinutes,
    entitlementId,
    namespace,
    returnTo,
    router,
    surface,
    target.calLink,
    target.origin,
  ]);

  useEffect(() => {
    if (!autoOpen || !ready || autoOpened.current) return;
    autoOpened.current = true;
    buttonRef.current?.click();
  }, [autoOpen, ready]);

  return (
    <button
      ref={buttonRef}
      type="button"
      data-cal-namespace={namespace}
      data-cal-link={target.calLink}
      data-cal-config={JSON.stringify(config)}
      disabled={!ready}
      onClick={() => {
        void fetch("/api/consultations/booking-opened", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ entitlementId, surface }),
          keepalive: true,
        });

        trackEvent("consultation_booking_clicked", {
          consultation_minutes: durationMinutes,
          surface,
        });
      }}
      className={
        className ??
        "inline-flex min-h-11 items-center justify-center rounded-full bg-teal-700 px-5 text-sm font-semibold text-white transition hover:bg-teal-800 disabled:cursor-wait disabled:opacity-60"
      }
    >
      {children ??
        (ready
          ? `Umów konsultację (${durationMinutes} min)`
          : "Ładowanie kalendarza…")}
    </button>
  );
}
