// @generated by install-humanet-values-marketing.mjs
"use client";

import type { ReactNode } from "react";

import { trackEvent } from "@/features/consent";

function buildBookingUrl({
  href,
  orderId,
  entitlementId,
}: {
  href: string;
  orderId: string | null;
  entitlementId: string;
}) {
  const url = new URL(href);

  if (orderId) {
    url.searchParams.set("metadata[orderId]", orderId);
  }

  url.searchParams.set(
    "metadata[consultationEntitlementId]",
    entitlementId,
  );
  url.searchParams.set("metadata[source]", "package");

  return url.toString();
}

export function ConsultationLink({
  href,
  durationMinutes,
  orderId,
  entitlementId,
  surface = "order_success",
  children,
}: {
  href: string;
  durationMinutes: number;
  orderId: string | null;
  entitlementId: string;
  surface?: string;
  children?: ReactNode;
}) {
  return (
    <a
      href={buildBookingUrl({ href, orderId, entitlementId })}
      target="_blank"
      rel="noreferrer"
      onClick={() =>
        trackEvent("consultation_booking_clicked", {
          consultation_minutes: durationMinutes,
          surface,
        })
      }
      className="inline-flex min-h-11 items-center justify-center rounded-full bg-teal-700 px-5 text-sm font-semibold text-white hover:bg-teal-800"
    >
      {children ?? `Umów konsultację (${durationMinutes} min)`}
    </a>
  );
}
