// @generated by install-humanet-values-consultations-v5.mjs
"use client";

import type { ReactNode } from "react";

import { CalBookingButton } from "./cal-booking-button";

export function ConsultationLink({
  href,
  durationMinutes,
  orderId,
  entitlementId,
  surface = "order_success",
  userEmail = null,
  userName = null,
  children,
}: {
  href: string;
  durationMinutes: number;
  orderId: string | null;
  entitlementId: string;
  surface?: string;
  userEmail?: string | null;
  userName?: string | null;
  children?: ReactNode;
}) {
  return (
    <CalBookingButton
      href={href}
      durationMinutes={durationMinutes}
      orderId={orderId}
      entitlementId={entitlementId}
      source="package"
      surface={surface}
      userEmail={userEmail}
      userName={userName}
    >
      {children}
    </CalBookingButton>
  );
}
