// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";
import {
  CalendarCheck2,
  CalendarPlus2,
  Clock3,
  ExternalLink,
  FileText,
  Video,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { getMyConsultationsData } from "../api/my-consultations.queries";
import { buildMyConsultationReportHref } from "../lib/consultation-report-link";
import { ConsultationLink } from "./consultation-link";

function formatDateTime(value: Date | null) {
  if (!value) return null;

  return new Intl.DateTimeFormat("pl-PL", {
    timeZone: "Europe/Warsaw",
    dateStyle: "long",
    timeStyle: "short",
  }).format(value);
}

function kindLabel(kind: string) {
  switch (kind) {
    case "decision_support":
      return "Wsparcie w decyzji";
    case "report_consultation":
      return "Konsultacja raportu";
    case "standalone":
      return "Konsultacja indywidualna";
    default:
      return "Konsultacja";
  }
}

function statusLabel(status: string) {
  switch (status) {
    case "available":
      return "Do umówienia";
    case "booked":
      return "Umówiona";
    case "completed":
      return "Zrealizowana";
    case "cancelled":
      return "Anulowana";
    case "expired":
      return "Wygasła";
    case "no_show":
      return "Nie odbyła się";
    default:
      return status;
  }
}

function includedBookingUrl(kind: string) {
  if (kind === "decision_support") {
    return process.env.NEXT_PUBLIC_CALCOM_DECISION_90_URL?.trim() || null;
  }

  return process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL?.trim() || null;
}

function buildStandaloneBookingUrl({
  baseUrl,
  email,
  name,
}: {
  baseUrl: string;
  email: string | null;
  name: string | null;
}) {
  const url = new URL(baseUrl);

  if (email) url.searchParams.set("email", email);
  if (name) url.searchParams.set("name", name);
  url.searchParams.set("metadata[source]", "standalone");

  return url.toString();
}

export async function MyConsultationsPage() {
  const { user, consultations } = await getMyConsultationsData();

  const standaloneBaseUrl =
    process.env.NEXT_PUBLIC_CALCOM_GENERAL_CONSULTATION_URL?.trim() ||
    process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL?.trim() ||
    null;

  const standaloneUrl = standaloneBaseUrl
    ? buildStandaloneBookingUrl({
        baseUrl: standaloneBaseUrl,
        email: user.email,
        name: user.name,
      })
    : null;

  const upcoming = consultations.filter(
    (item) => item.status === "booked",
  );
  const available = consultations.filter(
    (item) => item.status === "available",
  );
  const history = consultations.filter(
    (item) =>
      item.status !== "booked" && item.status !== "available",
  );

  return (
    <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6">
      <section className="rounded-[2rem] hv-brand-card p-6 sm:p-8">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="hv-brand-eyebrow">HUMANET VALUES</p>
            <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
              Moje konsultacje
            </h1>
            <p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">
              W tym miejscu wrócisz do konsultacji zawartych w pakietach,
              zobaczysz termin spotkania i przejdziesz do rozmowy.
            </p>
          </div>

          {standaloneUrl ? (
            <Button asChild variant="outline" className="rounded-full">
              <a href={standaloneUrl} target="_blank" rel="noreferrer">
                <CalendarPlus2 className="h-4 w-4" />
                Umów dodatkową konsultację
              </a>
            </Button>
          ) : null}
        </div>
      </section>

      <Section
        title="Nadchodzące"
        description="Umówione spotkania wraz z terminem i linkiem do rozmowy."
        items={upcoming}
      />

      <Section
        title="Do umówienia"
        description="Konsultacje z zakupionych pakietów, dla których termin nie został jeszcze wybrany."
        items={available}
      />

      {history.length > 0 ? (
        <Section
          title="Historia"
          description="Zrealizowane, anulowane lub wygasłe konsultacje."
          items={history}
        />
      ) : null}

      {consultations.length === 0 ? (
        <div className="mt-6 rounded-2xl border border-dashed bg-white p-6 text-sm leading-7 text-muted-foreground">
          Nie masz jeszcze konsultacji przypisanych do konta.
        </div>
      ) : null}
    </main>
  );
}

function Section({
  title,
  description,
  items,
}: {
  title: string;
  description: string;
  items: Awaited<
    ReturnType<typeof getMyConsultationsData>
  >["consultations"];
}) {
  return (
    <section className="mt-8">
      <div className="mb-4">
        <h2 className="text-xl font-semibold">{title}</h2>
        <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      </div>

      {items.length === 0 ? (
        <div className="rounded-2xl border border-dashed bg-white p-5 text-sm text-muted-foreground">
          Brak pozycji w tej sekcji.
        </div>
      ) : (
        <div className="grid gap-4">
          {items.map((item) => (
            <ConsultationCard key={item.id} item={item} />
          ))}
        </div>
      )}
    </section>
  );
}

function ConsultationCard({
  item,
}: {
  item: Awaited<
    ReturnType<typeof getMyConsultationsData>
  >["consultations"][number];
}) {
  const bookingUrl =
    item.status === "available" ? includedBookingUrl(item.kind) : null;
  const reportHref = buildMyConsultationReportHref(item.orderMetadata);
  const scheduled = formatDateTime(item.scheduledStartAt);

  return (
    <article className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center gap-2 rounded-full bg-neutral-100 px-3 py-1 text-xs font-semibold">
              <CalendarCheck2 className="h-3.5 w-3.5" />
              {statusLabel(item.status)}
            </span>
            <span className="text-sm font-semibold">
              {kindLabel(item.kind)}
            </span>
          </div>

          <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">
            <span className="inline-flex items-center gap-2">
              <Clock3 className="h-4 w-4" />
              {item.durationMinutes} min
            </span>
            {scheduled ? (
              <span className="font-medium text-foreground">
                {scheduled}
              </span>
            ) : null}
          </div>

          <p className="mt-3 text-xs text-muted-foreground">
            {item.source === "package"
              ? "Konsultacja zawarta w zakupionym pakiecie."
              : "Dodatkowa konsultacja umówiona niezależnie od pakietu."}
          </p>
        </div>

        <div className="flex flex-wrap gap-2 lg:justify-end">
          {bookingUrl && item.orderId ? (
            <ConsultationLink
              href={bookingUrl}
              durationMinutes={item.durationMinutes}
              orderId={item.orderId}
              entitlementId={item.id}
              surface="my_consultations"
            >
              Umów termin
            </ConsultationLink>
          ) : null}

          {item.meetingUrl ? (
            <Button asChild className="rounded-full">
              <a href={item.meetingUrl} target="_blank" rel="noreferrer">
                <Video className="h-4 w-4" />
                Dołącz do spotkania
              </a>
            </Button>
          ) : null}

          {item.rescheduleUrl ? (
            <Button asChild variant="outline" className="rounded-full">
              <a href={item.rescheduleUrl} target="_blank" rel="noreferrer">
                Zmień termin
                <ExternalLink className="h-4 w-4" />
              </a>
            </Button>
          ) : null}

          {reportHref ? (
            <Button asChild variant="ghost" className="rounded-full">
              <Link href={reportHref}>
                <FileText className="h-4 w-4" />
                Otwórz raport
              </Link>
            </Button>
          ) : null}
        </div>
      </div>

      {item.status === "booked" && !item.meetingUrl ? (
        <p className="mt-4 rounded-xl bg-neutral-50 p-3 text-xs leading-5 text-muted-foreground">
          Termin jest zapisany. Link do spotkania pojawi się tutaj po
          synchronizacji z systemem rezerwacji.
        </p>
      ) : null}
    </article>
  );
}
