// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { RetryReportPaymentForm } from "@/features/report-access";
import { PurchaseAnalytics } from "./purchase-analytics";
import { ConsultationLink } from "./consultation-link";

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

export function OrderSuccessPage({
  data,
}: {
  data: {
    order: {
      id: string;
      status: string;
      currency: string;
      totalGross: unknown;
      metadata: unknown;
    };
    entitlement: {
      id: string;
      kind: string;
      durationMinutes: number;
      status: string;
    } | null;
  };
}) {
  const metadata = asRecord(data.order.metadata);
  const sessionId =
    typeof metadata.assessmentSessionId === "string"
      ? metadata.assessmentSessionId
      : null;
  const tenantSlug =
    typeof metadata.tenantSlug === "string" ? metadata.tenantSlug : null;
  const reportTemplateVersionId =
    typeof metadata.reportTemplateVersionId === "string"
      ? metadata.reportTemplateVersionId
      : null;
  const projectQuestionnaireId =
    typeof metadata.projectQuestionnaireId === "string"
      ? metadata.projectQuestionnaireId
      : null;
  const questionnaireVersionId =
    typeof metadata.questionnaireVersionId === "string"
      ? metadata.questionnaireVersionId
      : null;
  const productCode =
    typeof metadata.productCode === "string" ? metadata.productCode : "report";
  const productName =
    typeof metadata.productName === "string"
      ? metadata.productName
      : "Raport HUMANET";

  const reportParams = new URLSearchParams();
  if (tenantSlug) reportParams.set("tenant", tenantSlug);
  if (projectQuestionnaireId) {
    reportParams.set("projectQuestionnaireId", projectQuestionnaireId);
  }
  if (questionnaireVersionId) {
    reportParams.set("questionnaireVersionId", questionnaireVersionId);
  }

  const reportHref =
    sessionId && reportTemplateVersionId && tenantSlug
      ? `/my/assessment/sessions/${sessionId}/report/${reportTemplateVersionId}?${reportParams}`
      : "/my/assessment";

  const isPaid = data.order.status === "paid";
  const isPending = data.order.status === "pending_payment";
  const gross = Number(data.order.totalGross);

  const calUrl =
    data.entitlement?.kind === "decision_support"
      ? process.env.NEXT_PUBLIC_CALCOM_DECISION_90_URL
      : process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL;

  return (
    <main className="min-h-screen hv-brand-surface px-4 py-10 sm:px-6">
      <section className="mx-auto max-w-2xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8">
        <h1 className="text-3xl font-semibold">
          {isPaid
            ? "Płatność została potwierdzona"
            : isPending
              ? "Oczekujemy na potwierdzenie płatności"
              : "Płatność nie została zakończona"}
        </h1>

        <p className="mt-4 text-sm leading-7 text-muted-foreground">
          {isPaid
            ? "Dostęp do pełnego raportu został aktywowany."
            : isPending
              ? "Źródłem prawdy jest webhook i weryfikacja operatora. Odśwież status albo wróć do płatności."
              : "Możesz bezpiecznie ponowić płatność."}
        </p>

        {isPaid ? (
          <>
            <PurchaseAnalytics
              orderId={data.order.id}
              currency={data.order.currency}
              value={Number.isFinite(gross) ? gross : 0}
              productCode={productCode}
              productName={productName}
            />

            <div className="mt-6 flex flex-wrap gap-3">
              <Button asChild>
                <Link href={reportHref}>Przejdź do pełnego raportu</Link>
              </Button>

              {data.entitlement ? (
                <Button asChild variant="outline">
                  <Link href="/my/consultations">Moje konsultacje</Link>
                </Button>
              ) : null}

              {data.entitlement && calUrl ? (
                <ConsultationLink
                  href={calUrl}
                  durationMinutes={data.entitlement.durationMinutes}
                  orderId={data.order.id}
                  entitlementId={data.entitlement.id}
                />
              ) : null}
            </div>

            {data.entitlement ? (
              <p className="mt-5 rounded-xl bg-neutral-50 p-4 text-sm leading-6 text-muted-foreground">
                Przeczytaj raport przed spotkaniem i zaznacz pytania, które
                chcesz omówić podczas konsultacji.
              </p>
            ) : null}
          </>
        ) : (
          <div className="mt-6 flex flex-wrap gap-3">
            <RetryReportPaymentForm
              orderId={data.order.id}
              label={isPending ? "Wróć do płatności" : "Spróbuj ponownie"}
            />
            <Button asChild variant="ghost">
              <Link href={`/my/orders/${data.order.id}/success`}>
                Odśwież status
              </Link>
            </Button>
          </div>
        )}

        <Button asChild variant="outline" className="mt-6">
          <Link href="/my/assessment">Wróć do panelu</Link>
        </Button>
      </section>
    </main>
  );
}
