// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { UnlockReportAccessPlaceholderForm } from "@/features/report-access";
import {
  getReportAccessOfferForCompletedSession,
} from "@/features/report-access/api/report-access.queries";
import { readReportAccessB2cOffer } from "@/features/report-access/lib/report-access-product-offer";
import type { purchaseIntents } from "@/drizzle/schema";

type PurchaseIntent = typeof purchaseIntents.$inferSelect;

function money(value: unknown, currency: string) {
  const numeric = Number(value);
  return Number.isFinite(numeric)
    ? new Intl.NumberFormat("pl-PL", {
        style: "currency",
        currency,
      }).format(numeric)
    : "—";
}

export async function PurchaseIntentCheckoutPage({
  intent,
}: {
  intent: PurchaseIntent;
}) {
  if (
    !intent.tenantSlug ||
    !intent.assessmentSessionId ||
    !intent.projectQuestionnaireId ||
    !intent.questionnaireVersionId
  ) {
    throw new Error("Proces zakupowy nie ma kompletnego powiązania z badaniem.");
  }

  const offer = await getReportAccessOfferForCompletedSession({
    tenantSlug: intent.tenantSlug,
    sessionId: intent.assessmentSessionId,
    expectedKind: "personal",
    projectQuestionnaireId: intent.projectQuestionnaireId,
    questionnaireVersionId: intent.questionnaireVersionId,
    productCode: intent.productCode,
  });

  if (!offer.ok) {
    return <State title="Nie można rozpocząć zakupu" message={offer.message} />;
  }

  if (offer.existingGrant) {
    return (
      <State
        title="Raport jest już odblokowany"
        message="Nie tworzymy drugiego zamówienia dla tego samego raportu."
      />
    );
  }

  if (!offer.product) {
    return (
      <State
        title="Produkt jest niedostępny"
        message="Produkt wybrany dla tej konfiguracji nie jest już aktywny dla tego raportu."
      />
    );
  }

  const b2cOffer = readReportAccessB2cOffer(offer.product.config);
  if (!b2cOffer || b2cOffer.offerCode !== intent.offerCode) {
    return (
      <State
        title="Konfiguracja produktu została zmieniona"
        message="Pakiet przypisany do produktu nie odpowiada rozpoczętemu procesowi. Wróć do strony startowej i wybierz ofertę ponownie."
      />
    );
  }

  return (
    <main className="min-h-screen hv-brand-surface px-4 py-8 sm:px-6">
      <div className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8">
        <p className="hv-brand-eyebrow">HUMANET VALUES</p>
        <h1 className="mt-3 text-3xl font-semibold">Podsumowanie zakupu</h1>
        <p className="mt-3 text-sm leading-6 text-muted-foreground">
          Cena, VAT, waluta, pakiet i wersja raportu zostały ponownie
          zweryfikowane po stronie serwera.
        </p>

        <div className="mt-6 grid gap-3 sm:grid-cols-2">
          <div className="rounded-xl border p-4">
            <p className="text-xs text-muted-foreground">Produkt</p>
            <p className="mt-1 font-semibold">{offer.product.name}</p>
          </div>
          <div className="rounded-xl border p-4">
            <p className="text-xs text-muted-foreground">Cena brutto</p>
            <p className="mt-1 font-semibold">
              {money(offer.product.priceGross, offer.product.currency)}
            </p>
          </div>
        </div>

        {b2cOffer.consultation ? (
          <p className="mt-4 rounded-xl bg-neutral-50 p-4 text-sm text-muted-foreground">
            Pakiet obejmuje konsultację: {b2cOffer.consultation.durationMinutes} min.
          </p>
        ) : null}

        <UnlockReportAccessPlaceholderForm
          tenantSlug={intent.tenantSlug}
          sessionId={intent.assessmentSessionId}
          originalAmountCents={Math.round(Number(offer.product.priceGross) * 100)}
          currency={offer.product.currency}
          productId={offer.product.id}
          reportTemplateVersionId={
            offer.reportVersion.reportTemplateVersionId
          }
          projectQuestionnaireId={intent.projectQuestionnaireId}
          questionnaireVersionId={intent.questionnaireVersionId}
          purchaseIntentId={intent.id}
        />

        <Button asChild variant="ghost" className="mt-4">
          <Link href="/my/assessment">Wróć do badań</Link>
        </Button>
      </div>
    </main>
  );
}

function State({ title, message }: { title: string; message: string }) {
  return (
    <main className="flex min-h-[70vh] items-center justify-center px-4">
      <section className="max-w-xl rounded-2xl border bg-white p-8">
        <h1 className="text-2xl font-semibold">{title}</h1>
        <p className="mt-3 text-sm leading-6 text-muted-foreground">{message}</p>
        <Button asChild className="mt-6">
          <Link href="/my/assessment">Wróć do badań</Link>
        </Button>
      </section>
    </main>
  );
}
