// @generated by install-humanet-values-consultations-v5.mjs
"use client";

import { useState } from "react";
import { CalendarPlus2 } from "lucide-react";

import { CalBookingButton } from "./cal-booking-button";

type Draft = {
  entitlementId: string;
  orderId: string | null;
  durationMinutes: number;
  bookingUrl: string;
  userEmail: string | null;
  userName: string | null;
};

export function StandaloneConsultationButton() {
  const [draft, setDraft] = useState<Draft | null>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (draft) {
    return (
      <CalBookingButton
        href={draft.bookingUrl}
        entitlementId={draft.entitlementId}
        orderId={draft.orderId}
        durationMinutes={draft.durationMinutes}
        source="standalone"
        surface="my_consultations_new"
        userEmail={draft.userEmail}
        userName={draft.userName}
        autoOpen
        returnTo="/my/consultations"
        className="inline-flex min-h-10 items-center justify-center rounded-full border border-black/10 bg-white px-4 text-sm font-semibold transition hover:bg-neutral-50"
      >
        <CalendarPlus2 className="mr-2 h-4 w-4" />
        Dokończ rezerwację
      </CalBookingButton>
    );
  }

  return (
    <div className="flex flex-col items-start gap-2">
      <button
        type="button"
        disabled={pending}
        onClick={async () => {
          setPending(true);
          setError(null);

          try {
            const response = await fetch("/api/consultations/standalone", {
              method: "POST",
            });
            const body = (await response.json()) as Partial<Draft> & {
              ok?: boolean;
            };

            if (
              !response.ok ||
              body.ok !== true ||
              !body.entitlementId ||
              !body.bookingUrl ||
              !body.durationMinutes
            ) {
              throw new Error("Nie można rozpocząć rezerwacji.");
            }

            setDraft({
              entitlementId: body.entitlementId,
              orderId: body.orderId ?? null,
              durationMinutes: body.durationMinutes,
              bookingUrl: body.bookingUrl,
              userEmail: body.userEmail ?? null,
              userName: body.userName ?? null,
            });
          } catch {
            setError("Nie udało się otworzyć kalendarza. Spróbuj ponownie.");
          } finally {
            setPending(false);
          }
        }}
        className="inline-flex min-h-10 items-center justify-center rounded-full border border-black/10 bg-white px-4 text-sm font-semibold transition hover:bg-neutral-50 disabled:opacity-60"
      >
        <CalendarPlus2 className="mr-2 h-4 w-4" />
        {pending ? "Przygotowuję kalendarz…" : "Umów dodatkową konsultację"}
      </button>

      {error ? <p className="text-xs text-red-700">{error}</p> : null}
    </div>
  );
}
