// @generated by install-humanet-values-marketing.mjs
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { getPurchaseFlowConfig } from "../config/purchase-flow.config";
import type {
  OfferCode,
  ReportType,
} from "../types/purchase-flow.types";
import { ReportTypeLink } from "./report-type-link";
import { startPurchaseFlowAction } from "../api/start-purchase-flow.action";
import { resolvePurchaseCombination } from "../api/purchase-flow.queries";

function money(value: unknown, currency: string) {
  const numeric = Number(value);
  return Number.isFinite(numeric)
    ? new Intl.NumberFormat("pl-PL", {
        style: "currency",
        currency,
      }).format(numeric)
    : "—";
}

type Props = {
  isAuthenticated: boolean;
  offerCode: OfferCode | null;
  reportType: ReportType | null;
  passthrough: Record<string, string>;
};

function buildStartHref(
  input: Record<string, string | null | undefined>,
): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(input)) {
    if (value) params.set(key, value);
  }
  return `/start?${params.toString()}`;
}

export async function StartFlowPage({
  isAuthenticated,
  offerCode,
  reportType,
  passthrough,
}: Props) {
  const config = getPurchaseFlowConfig();

  if (!offerCode) {
    return (
      <Shell
        title="Wybierz zakres wsparcia"
        description="Cena i warunki oferty są rozwiązywane po stronie serwera w aplikacji HUMANET VALUES."
      >
        <div className="grid gap-4 md:grid-cols-3">
          {Object.values(config.offers).map((offer) => (
            <Link
              key={offer.code}
              href={buildStartHref({
                ...passthrough,
                offer: offer.code,
              })}
              className="rounded-2xl border border-black/10 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"
            >
              <h2 className="font-semibold">{offer.label}</h2>
              <p className="mt-2 text-sm leading-6 text-muted-foreground">
                {offer.description}
              </p>
            </Link>
          ))}
        </div>
      </Shell>
    );
  }

  if (!reportType) {
    return (
      <Shell
        title="Co chcesz teraz lepiej zrozumieć?"
        description={`Wybrana oferta: ${config.offers[offerCode].label}. Rodzaj raportu możesz zmienić przed rozpoczęciem kwestionariusza.`}
      >
        <div className="grid gap-4 md:grid-cols-3">
          {Object.values(config.reports).map((report) => (
            <ReportTypeLink
              key={report.code}
              reportType={report.code}
              href={buildStartHref({
                ...passthrough,
                offer: offerCode,
                reportType: report.code,
              })}
            >
              <h2 className="font-semibold">{report.label}</h2>
              <p className="mt-2 text-sm leading-6 text-muted-foreground">
                {report.description}
              </p>
              <p className="mt-4 text-xs font-medium text-teal-800">
                Około 15–25 minut
              </p>
            </ReportTypeLink>
          ))}
        </div>
      </Shell>
    );
  }

  const combination = await resolvePurchaseCombination({
    offerCode,
    reportType,
  });

  if (!combination.ok) {
    return (
      <Shell
        title="Ta konfiguracja nie jest jeszcze dostępna"
        description={combination.message}
      >
        <Button asChild variant="outline" className="rounded-full">
          <Link href={buildStartHref({ ...passthrough, offer: offerCode })}>
            Wybierz inny raport
          </Link>
        </Button>
      </Shell>
    );
  }

  const callbackUrl = buildStartHref({
    ...passthrough,
    offer: offerCode,
    reportType,
  });
  const consultation = combination.b2cOffer.consultation;

  if (!isAuthenticated) {
    return (
      <Shell
        title="Zapisz wybrany proces"
        description="Zaloguj się jednorazowym linkiem. Po powrocie oferta i rodzaj raportu pozostaną wybrane."
      >
        <div className="rounded-2xl border bg-white p-6">
          <p className="font-semibold">
            {combination.offer.label} · {combination.report.label}
          </p>
          <p className="mt-2 text-sm text-muted-foreground">
            {combination.product.name} · {money(
              combination.product.priceGross,
              combination.product.currency,
            )}
            {consultation
              ? ` · konsultacja ${consultation.durationMinutes} min`
              : ""}
          </p>
          <Button asChild className="mt-5 rounded-full">
            <Link
              href={`/login?callbackUrl=${encodeURIComponent(callbackUrl)}`}
            >
              Zaloguj się i rozpocznij
            </Link>
          </Button>
        </div>
      </Shell>
    );
  }

  return (
    <Shell
      title="Potwierdź wybrany kwestionariusz"
      description="System wznowi istniejącą aktywną sesję albo utworzy jedną nową. Nie nadpisze sesji innego rodzaju raportu."
    >
      <form action={startPurchaseFlowAction} className="rounded-2xl border bg-white p-6">
        <input type="hidden" name="offerCode" value={offerCode} />
        <input type="hidden" name="reportType" value={reportType} />
        <input type="hidden" name="callbackUrl" value={callbackUrl} />
        <input
          type="hidden"
          name="attributionSearchParams"
          value={JSON.stringify(passthrough)}
        />

        <p className="text-sm text-muted-foreground">Oferta</p>
        <p className="mt-1 font-semibold">{combination.offer.label}</p>
        <p className="mt-5 text-sm text-muted-foreground">Raport</p>
        <p className="mt-1 font-semibold">{combination.report.label}</p>
        <p className="mt-5 text-sm text-muted-foreground">Cena</p>
        <p className="mt-1 font-semibold">
          {money(
            combination.product.priceGross,
            combination.product.currency,
          )}
        </p>
        {consultation ? (
          <p className="mt-2 text-sm text-muted-foreground">
            Pakiet obejmuje konsultację: {consultation.durationMinutes} min.
          </p>
        ) : null}

        <div className="mt-6 flex flex-wrap gap-3">
          <Button type="submit" className="rounded-full">
            Rozpocznij lub kontynuuj badanie
          </Button>
          <Button asChild type="button" variant="outline" className="rounded-full">
            <Link href={buildStartHref({ ...passthrough, offer: offerCode })}>
              Zmień rodzaj raportu
            </Link>
          </Button>
        </div>
      </form>
    </Shell>
  );
}

function Shell({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen hv-brand-surface px-4 py-10 sm:px-6">
      <div className="mx-auto w-full max-w-5xl">
        <div className="mb-8">
          <p className="hv-brand-eyebrow">HUMANET VALUES</p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">
            {title}
          </h1>
          <p className="mt-4 max-w-3xl text-base leading-8 text-muted-foreground">
            {description}
          </p>
        </div>
        {children}
      </div>
    </main>
  );
}
