// @generated by install-humanet-values-marketing.mjs
import { notFound } from "next/navigation";

import {
  getOwnedMarketingOrder,
  OrderSuccessPage,
} from "@/features/purchase-flow";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function Page({
  params,
}: {
  params: Promise<{ orderId: string }>;
}) {
  const { orderId } = await params;
  const data = await getOwnedMarketingOrder(orderId);

  if (!data) notFound();

  return <OrderSuccessPage data={data} />;
}
