// @generated by install-humanet-values-marketing.mjs
import type {
  AttributionSnapshot,
  AttributionTouch,
} from "../types/attribution.types";

export const ATTRIBUTION_COOKIE_NAME = "humanet_attribution_v1";
const MAX_AGE = 60 * 60 * 24 * 90;

function isTouch(value: unknown): value is AttributionTouch {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const row = value as Record<string, unknown>;
  return typeof row.landingPage === "string" && typeof row.capturedAt === "string";
}

export function parseAttributionCookie(
  raw: string | null | undefined,
): AttributionSnapshot | null {
  if (!raw) return null;

  try {
    const parsed = JSON.parse(decodeURIComponent(raw)) as {
      firstTouch?: unknown;
      lastTouch?: unknown;
    };

    if (!isTouch(parsed.firstTouch) || !isTouch(parsed.lastTouch)) return null;

    return {
      firstTouch: parsed.firstTouch,
      lastTouch: parsed.lastTouch,
    };
  } catch {
    return null;
  }
}

export function writeAttributionCookie(snapshot: AttributionSnapshot): void {
  if (typeof document === "undefined" || typeof window === "undefined") return;

  const attributes = [
    `${ATTRIBUTION_COOKIE_NAME}=${encodeURIComponent(JSON.stringify(snapshot))}`,
    "Path=/",
    `Max-Age=${MAX_AGE}`,
    "SameSite=Lax",
  ];

  if (window.location.protocol === "https:") attributes.push("Secure");
  if (
    window.location.hostname === "humanet.me" ||
    window.location.hostname.endsWith(".humanet.me")
  ) {
    attributes.push("Domain=.humanet.me");
  }

  document.cookie = attributes.join("; ");
}
