// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { cookies } from "next/headers";

import {
  HUMANET_CONSENT_COOKIE_NAME,
} from "@/features/consent/types/consent.types";
import { parseConsentState } from "@/features/consent/lib/consent-cookie";
import {
  ATTRIBUTION_COOKIE_NAME,
  parseAttributionCookie,
} from "./attribution-cookie";
import type {
  AttributionSnapshot,
  AttributionTouch,
} from "../types/attribution.types";

type SearchParams = Record<string, string | string[] | undefined>;

function one(value: string | string[] | undefined): string | null {
  const candidate = Array.isArray(value) ? value[0] : value;
  const normalized = candidate?.trim();
  return normalized || null;
}

export async function readAttributionForRequest(
  searchParams: SearchParams,
): Promise<AttributionSnapshot | null> {
  const store = await cookies();
  const consentVersion =
    process.env.NEXT_PUBLIC_CONSENT_VERSION?.trim() || "2026-08-01";
  const consent = parseConsentState(
    store.get(HUMANET_CONSENT_COOKIE_NAME)?.value,
    consentVersion,
  );

  if (!consent?.analytics) return null;

  const cookieSnapshot = parseAttributionCookie(
    store.get(ATTRIBUTION_COOKIE_NAME)?.value,
  );

  const hasCampaign =
    Boolean(one(searchParams.utm_source)) ||
    Boolean(one(searchParams.utm_medium)) ||
    Boolean(one(searchParams.utm_campaign)) ||
    Boolean(one(searchParams.ref)) ||
    Boolean(one(searchParams.partner));

  if (!hasCampaign) return cookieSnapshot;

  const appUrl = process.env.APP_URL?.replace(/\/+$/, "") || "";
  const query = new URLSearchParams();

  for (const key of [
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_content",
    "utm_term",
    "ref",
    "partner",
  ]) {
    const current = one(searchParams[key]);
    if (current) query.set(key, current);
  }

  const touch: AttributionTouch = {
    source: one(searchParams.utm_source),
    medium: one(searchParams.utm_medium),
    campaign: one(searchParams.utm_campaign),
    content: one(searchParams.utm_content),
    term: one(searchParams.utm_term),
    landingPage: `${appUrl}/start${query.size ? `?${query}` : ""}`,
    referrer: null,
    capturedAt: new Date().toISOString(),
    ref: one(searchParams.ref),
    partner: one(searchParams.partner),
  };

  return {
    firstTouch: cookieSnapshot?.firstTouch ?? touch,
    lastTouch: touch,
  };
}
