// @generated by install-humanet-values-marketing.mjs
export { ConsentProvider, useConsent } from "./components/consent-provider";
export { DynamicAnalytics } from "./components/dynamic-analytics";
export { trackEvent } from "./lib/track-event";
export {
  parseConsentState,
  readConsentCookie,
  writeConsentCookie,
} from "./lib/consent-cookie";
export type { ConsentState } from "./types/consent.types";
