// @generated by install-humanet-values-marketing.mjs
"use server";

import { redirect } from "next/navigation";

import { requireSession } from "@/server/auth/require-session";
import { safeInternalCallback } from "@/features/purchase-flow/forms/start-flow.schema";
import { recordCurrentTermsAcceptance } from "./legal.mutations";

export async function acceptCurrentLegalDocumentsAction(formData: FormData) {
  const session = await requireSession();

  if (formData.get("acceptTerms") !== "on") {
    throw new Error("Aby kontynuować, zaakceptuj regulamin.");
  }

  await recordCurrentTermsAcceptance({
    userId: session.user.id,
    source: "legacy_legal_action",
  });

  redirect(
    safeInternalCallback(
      String(formData.get("callbackUrl") ?? ""),
      "/my/assessment",
    ),
  );
}
