// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { legalAcceptances } from "@/drizzle/schema";
import { writeSystemAuditLog } from "@/server/audit/write-system-audit-log";
import { controlDb } from "@/server/db/control-db";
import { getCurrentLegalDocument } from "./legal.queries";

export async function recordCurrentTermsAcceptance({
  userId,
  source,
  metadata = {},
}: {
  userId: string;
  source: string;
  metadata?: Record<string, unknown>;
}) {
  const terms = await getCurrentLegalDocument("terms");

  if (!terms) {
    throw new Error("Nie udało się ustalić aktualnej wersji regulaminu.");
  }

  const now = new Date();
  const [created] = await controlDb
    .insert(legalAcceptances)
    .values({
      userId,
      documentId: terms.id,
      acceptedAt: now,
      source,
      createdAt: now,
    })
    .onConflictDoNothing({
      target: [legalAcceptances.userId, legalAcceptances.documentId],
    })
    .returning();

  if (created) {
    await writeSystemAuditLog({
      actorUserId: userId,
      actorRole: "USER",
      action: "legal.terms_accepted",
      entityType: "legal_document",
      entityId: terms.id,
      after: {
        version: terms.version,
        source,
        ...metadata,
      },
    });
  }

  return terms;
}
