// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, eq } from "drizzle-orm";

import { legalAcceptances, legalDocuments } from "@/drizzle/schema";
import { controlDb } from "@/server/db/control-db";
import { CURRENT_LEGAL_DOCUMENTS } from "../config/legal-documents.config";

export async function ensureCurrentLegalDocuments() {
  const now = new Date();

  for (const document of CURRENT_LEGAL_DOCUMENTS) {
    const existing = await controlDb.query.legalDocuments.findFirst({
      where: and(
        eq(legalDocuments.type, document.type),
        eq(legalDocuments.version, document.version),
      ),
    });

    if (!existing) {
      await controlDb.insert(legalDocuments).values({
        type: document.type,
        version: document.version,
        contentHash: document.contentHash,
        effectiveFrom: now,
        isActive: true,
        createdAt: now,
        updatedAt: now,
      });
    }

    await controlDb
      .update(legalDocuments)
      .set({ isActive: false, updatedAt: now })
      .where(eq(legalDocuments.type, document.type));

    await controlDb
      .update(legalDocuments)
      .set({
        isActive: true,
        contentHash: document.contentHash,
        updatedAt: now,
      })
      .where(
        and(
          eq(legalDocuments.type, document.type),
          eq(legalDocuments.version, document.version),
        ),
      );
  }
}

export async function getCurrentLegalDocument(type: "terms" | "privacy_notice") {
  await ensureCurrentLegalDocuments();

  return (
    (await controlDb.query.legalDocuments.findFirst({
      where: and(
        eq(legalDocuments.type, type),
        eq(legalDocuments.isActive, true),
      ),
    })) ?? null
  );
}

export async function hasCurrentTermsAcceptance(userId: string) {
  const terms = await getCurrentLegalDocument("terms");
  if (!terms) return false;

  const acceptance = await controlDb.query.legalAcceptances.findFirst({
    where: and(
      eq(legalAcceptances.userId, userId),
      eq(legalAcceptances.documentId, terms.id),
    ),
  });

  return Boolean(acceptance);
}
