// @generated by install-humanet-values-marketing.mjs
import {
  index,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  integer,
} from "drizzle-orm/pg-core";

import { users } from "./users";

export const consultationEntitlements = pgTable(
  "consultation_entitlements",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orderId: uuid("order_id").notNull(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    kind: varchar("kind", { length: 60 }).notNull(),
    durationMinutes: integer("duration_minutes").notNull(),
    status: varchar("status", { length: 30 })
      .notNull()
      .default("available"),
    bookingProvider: varchar("booking_provider", { length: 40 })
      .notNull()
      .default("calcom"),
    bookingReference: varchar("booking_reference", { length: 255 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    bookedAt: timestamp("booked_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    orderUnique: uniqueIndex("consultation_entitlements_order_unique").on(
      table.orderId,
    ),
    userIdx: index("consultation_entitlements_user_idx").on(table.userId),
    statusIdx: index("consultation_entitlements_status_idx").on(table.status),
  }),
);
