// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { desc, eq } from "drizzle-orm";

import {
  consultationEntitlements,
  reportAccessOrders,
  users,
} from "@/drizzle/schema";
import { requireSuperAdmin } from "@/server/auth/require-super-admin";
import { controlDb } from "@/server/db/control-db";

export async function listConsultationEntitlementsAdmin() {
  await requireSuperAdmin();

  return controlDb
    .select({
      id: consultationEntitlements.id,
      orderId: consultationEntitlements.orderId,
      userId: consultationEntitlements.userId,
      userEmail: users.email,
      kind: consultationEntitlements.kind,
      durationMinutes: consultationEntitlements.durationMinutes,
      status: consultationEntitlements.status,
      bookingReference: consultationEntitlements.bookingReference,
      createdAt: consultationEntitlements.createdAt,
      bookedAt: consultationEntitlements.bookedAt,
      completedAt: consultationEntitlements.completedAt,
      orderStatus: reportAccessOrders.status,
    })
    .from(consultationEntitlements)
    .innerJoin(users, eq(users.id, consultationEntitlements.userId))
    .leftJoin(
      reportAccessOrders,
      eq(reportAccessOrders.id, consultationEntitlements.orderId),
    )
    .orderBy(desc(consultationEntitlements.createdAt));
}
