// @generated by install-humanet-values-marketing.mjs
"use server";

import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";

import { consultationEntitlements } from "@/drizzle/schema";
import { writeSystemAuditLog } from "@/server/audit/write-system-audit-log";
import { requireSuperAdmin } from "@/server/auth/require-super-admin";
import { controlDb } from "@/server/db/control-db";

const statusSchema = z.enum([
  "available",
  "booked",
  "completed",
  "expired",
  "cancelled",
]);

export async function updateConsultationEntitlementAction(
  formData: FormData,
) {
  const admin = await requireSuperAdmin();
  const entitlementId = z.string().uuid().parse(formData.get("entitlementId"));
  const status = statusSchema.parse(formData.get("status"));
  const bookingReferenceRaw = formData.get("bookingReference");
  const bookingReference =
    typeof bookingReferenceRaw === "string" &&
    bookingReferenceRaw.trim()
      ? bookingReferenceRaw.trim()
      : null;
  const now = new Date();

  const [before] = await controlDb
    .select()
    .from(consultationEntitlements)
    .where(eq(consultationEntitlements.id, entitlementId))
    .limit(1);

  if (!before) {
    throw new Error("Nie znaleziono uprawnienia konsultacyjnego.");
  }

  await controlDb
    .update(consultationEntitlements)
    .set({
      status,
      bookingReference,
      bookedAt:
        status === "booked" || status === "completed"
          ? before.bookedAt ?? now
          : before.bookedAt,
      completedAt: status === "completed" ? now : null,
      cancelledAt: status === "cancelled" ? now : null,
      updatedAt: now,
    })
    .where(eq(consultationEntitlements.id, entitlementId));

  await writeSystemAuditLog({
    actorUserId: admin.id,
    actorRole: "SUPER_ADMIN",
    action: "consultation_entitlement.updated",
    entityType: "consultation_entitlement",
    entityId: entitlementId,
    before: {
      status: before.status,
      bookingReference: before.bookingReference,
    },
    after: { status, bookingReference },
  });

  revalidatePath("/dashboard/consultations");
}
