// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, eq, isNull } from "drizzle-orm";

import {
  consultationEntitlements,
  purchaseIntents,
  reportAccessOrders,
  reportAccessProducts,
} from "@/drizzle/schema";
import { readReportAccessB2cOffer } from "@/features/report-access/lib/report-access-product-offer";
import { writeSystemAuditLog } from "@/server/audit/write-system-audit-log";
import { controlDb } from "@/server/db/control-db";
import type { PurchaseIntentInput } from "../types/purchase-flow.types";

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

export async function createOrResumePurchaseIntent({
  userId,
  input,
}: {
  userId: string;
  input: PurchaseIntentInput;
}) {
  const existing = await controlDb.query.purchaseIntents.findFirst({
    where: and(
      eq(purchaseIntents.userId, userId),
      eq(purchaseIntents.assessmentSessionId, input.assessmentSessionId),
      eq(purchaseIntents.offerCode, input.offerCode),
      isNull(purchaseIntents.deletedAt),
    ),
  });

  const now = new Date();

  if (existing) {
    const [updated] = await controlDb
      .update(purchaseIntents)
      .set({
        reportType: input.reportType,
        productCode: input.productCode,
        status:
          existing.status === "paid"
            ? "paid"
            : "questionnaire_started",
        tenantSlug: input.tenantSlug,
        questionnaireVersionId: input.questionnaireVersionId,
        projectQuestionnaireId: input.projectQuestionnaireId,
        attribution: input.attribution,
        updatedAt: now,
      })
      .where(eq(purchaseIntents.id, existing.id))
      .returning();

    return updated;
  }

  const [created] = await controlDb
    .insert(purchaseIntents)
    .values({
      userId,
      offerCode: input.offerCode,
      reportType: input.reportType,
      productCode: input.productCode,
      status: "questionnaire_started",
      tenantSlug: input.tenantSlug,
      questionnaireVersionId: input.questionnaireVersionId,
      projectQuestionnaireId: input.projectQuestionnaireId,
      assessmentSessionId: input.assessmentSessionId,
      attribution: input.attribution,
      metadata: {},
      createdAt: now,
      updatedAt: now,
    })
    .returning();

  await writeSystemAuditLog({
    actorUserId: userId,
    actorRole: "USER",
    action: "purchase_intent.created",
    entityType: "purchase_intent",
    entityId: created.id,
    after: {
      offerCode: input.offerCode,
      reportType: input.reportType,
      productCode: input.productCode,
      assessmentSessionId: input.assessmentSessionId,
    },
  });

  return created;
}

export async function markPurchaseIntentCheckoutStarted({
  purchaseIntentId,
  userId,
  orderId,
}: {
  purchaseIntentId: string;
  userId: string;
  orderId: string;
}) {
  const [updated] = await controlDb
    .update(purchaseIntents)
    .set({
      status: "checkout_started",
      orderId,
      updatedAt: new Date(),
    })
    .where(
      and(
        eq(purchaseIntents.id, purchaseIntentId),
        eq(purchaseIntents.userId, userId),
        isNull(purchaseIntents.deletedAt),
      ),
    )
    .returning();

  if (!updated) {
    throw new Error("Nie udało się powiązać zamówienia z procesem zakupowym.");
  }

  return updated;
}

export async function finalizeMarketingPurchaseOrder({
  orderId,
}: {
  orderId: string;
}) {
  const order = await controlDb.query.reportAccessOrders.findFirst({
    where: and(
      eq(reportAccessOrders.id, orderId),
      isNull(reportAccessOrders.deletedAt),
    ),
  });

  if (!order || order.status !== "paid" || !order.buyerUserId) {
    return { handled: false as const };
  }

  const metadata = asRecord(order.metadata);
  const purchaseIntentId =
    typeof metadata.purchaseIntentId === "string"
      ? metadata.purchaseIntentId
      : null;

  if (!purchaseIntentId) {
    return { handled: false as const };
  }

  const intent = await controlDb.query.purchaseIntents.findFirst({
    where: and(
      eq(purchaseIntents.id, purchaseIntentId),
      eq(purchaseIntents.userId, order.buyerUserId),
      isNull(purchaseIntents.deletedAt),
    ),
  });

  if (!intent) {
    return { handled: false as const };
  }

  const now = new Date();

  await controlDb
    .update(purchaseIntents)
    .set({
      status: "paid",
      orderId: order.id,
      paidAt: order.paidAt ?? now,
      updatedAt: now,
    })
    .where(eq(purchaseIntents.id, intent.id));

  let purchasedOffer = readReportAccessB2cOffer(metadata.b2cOffer);

  if (!purchasedOffer) {
    const product = await controlDb.query.reportAccessProducts.findFirst({
      where: eq(reportAccessProducts.code, intent.productCode),
    });
    purchasedOffer = readReportAccessB2cOffer(product?.config);
  }

  if (
    purchasedOffer &&
    purchasedOffer.offerCode === intent.offerCode &&
    purchasedOffer.consultation
  ) {
    await controlDb
      .insert(consultationEntitlements)
      .values({
        orderId: order.id,
        userId: order.buyerUserId,
        kind: purchasedOffer.consultation.kind,
        durationMinutes: purchasedOffer.consultation.durationMinutes,
        status: "available",
        bookingProvider: "calcom",
        createdAt: now,
        updatedAt: now,
      })
      .onConflictDoNothing({
        target: consultationEntitlements.orderId,
      });
  }

  await writeSystemAuditLog({
    actorUserId: order.buyerUserId,
    actorRole: "USER",
    action: "marketing_purchase.fulfilled",
    entityType: "report_access_order",
    entityId: order.id,
    after: {
      purchaseIntentId: intent.id,
      offerCode: intent.offerCode,
      productCode: intent.productCode,
      consultationMinutes:
        purchasedOffer?.consultation?.durationMinutes ?? null,
    },
  });

  return { handled: true as const };
}
