// @generated by install-humanet-values-marketing.mjs
import { notFound } from "next/navigation";

import {
  finalizeMarketingPurchaseOrder,
  getOwnedMarketingOrder,
  OrderSuccessPage,
} from "@/features/purchase-flow";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function Page({
  params,
}: {
  params: Promise<{ orderId: string }>;
}) {
  const { orderId } = await params;
  let data = await getOwnedMarketingOrder(orderId);

  if (!data) notFound();

  /**
   * @humanet-consultation-paid-order-self-heal-v5-1
   *
   * Payment verification/report grant remains the source of truth.
   * This only retries idempotent marketing fulfillment for an order that
   * is already marked as paid. It never marks a pending order as paid.
   */
  if (data.order.status === "paid") {
    await finalizeMarketingPurchaseOrder({ orderId });
    data = (await getOwnedMarketingOrder(orderId)) ?? data;
  }

  return <OrderSuccessPage data={data} />;
}
