// @generated by install-humanet-values-marketing.mjs
import { ConsultationsAdminPage } from "@/features/purchase-flow/components/consultations-admin-page";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function Page() {
  return <ConsultationsAdminPage />;
}
