// @generated by install-humanet-values-marketing.mjs
import {
  HUMANET_CONSENT_COOKIE_NAME,
  HUMANET_CONSENT_MAX_AGE_SECONDS,
  type ConsentState,
} from "../types/consent.types";

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

export function parseConsentState(
  rawValue: string | null | undefined,
  expectedVersion: string,
): ConsentState | null {
  if (!rawValue) return null;

  try {
    const value = JSON.parse(decodeURIComponent(rawValue)) as unknown;

    if (
      !isRecord(value) ||
      value.necessary !== true ||
      typeof value.analytics !== "boolean" ||
      typeof value.marketing !== "boolean" ||
      typeof value.version !== "string" ||
      typeof value.updatedAt !== "string" ||
      value.version !== expectedVersion
    ) {
      return null;
    }

    return {
      necessary: true,
      analytics: value.analytics,
      marketing: value.marketing,
      version: value.version,
      updatedAt: value.updatedAt,
    };
  } catch {
    return null;
  }
}

export function readConsentCookie(expectedVersion: string): ConsentState | null {
  if (typeof document === "undefined") return null;

  const prefix = `${HUMANET_CONSENT_COOKIE_NAME}=`;
  const rawValue = document.cookie
    .split(";")
    .map((item) => item.trim())
    .find((item) => item.startsWith(prefix))
    ?.slice(prefix.length);

  return parseConsentState(rawValue, expectedVersion);
}

function usesHumanetParentDomain(hostname: string): boolean {
  return hostname === "humanet.me" || hostname.endsWith(".humanet.me");
}

export function writeConsentCookie(state: ConsentState): void {
  if (typeof document === "undefined" || typeof window === "undefined") return;

  const attributes = [
    `${HUMANET_CONSENT_COOKIE_NAME}=${encodeURIComponent(JSON.stringify(state))}`,
    "Path=/",
    `Max-Age=${HUMANET_CONSENT_MAX_AGE_SECONDS}`,
    "SameSite=Lax",
  ];

  if (window.location.protocol === "https:") attributes.push("Secure");
  if (usesHumanetParentDomain(window.location.hostname)) {
    attributes.push("Domain=.humanet.me");
  }

  document.cookie = attributes.join("; ");
}

function expireCookie(name: string, domain?: string): void {
  const parts = [
    `${name}=`,
    "Path=/",
    "Max-Age=0",
    "Expires=Thu, 01 Jan 1970 00:00:00 GMT",
    "SameSite=Lax",
  ];

  if (domain) parts.push(`Domain=${domain}`);
  if (typeof window !== "undefined" && window.location.protocol === "https:") {
    parts.push("Secure");
  }

  document.cookie = parts.join("; ");
}

export function removeKnownAnalyticsCookies(): void {
  if (typeof document === "undefined" || typeof window === "undefined") return;

  const names = document.cookie
    .split(";")
    .map((item) => item.trim().split("=")[0])
    .filter(Boolean)
    .filter(
      (name) =>
        name === "_ga" ||
        name === "_gid" ||
        name === "_gat" ||
        name.startsWith("_ga_") ||
        name === "_clck" ||
        name === "_clsk",
    );

  for (const name of names) {
    expireCookie(name);
    expireCookie(name, window.location.hostname);
    if (usesHumanetParentDomain(window.location.hostname)) {
      expireCookie(name, ".humanet.me");
    }
  }
}
