// @generated by install-humanet-values-consultations-v5.mjs
import "server-only";

export type HumanetConsultationKind =
  | "report_consultation"
  | "decision_support"
  | "standalone";

function clean(value: string | undefined): string | null {
  const result = value?.trim();
  return result || null;
}

export function getCalComBookingUrlForKind(
  kind: HumanetConsultationKind,
): string | null {
  if (kind === "decision_support") {
    return clean(process.env.NEXT_PUBLIC_CALCOM_DECISION_90_URL);
  }

  if (kind === "standalone") {
    return (
      clean(process.env.NEXT_PUBLIC_CALCOM_GENERAL_CONSULTATION_URL) ??
      clean(process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL)
    );
  }

  return clean(process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL);
}

export function getStandaloneConsultationMinutes(): number {
  const value = Number(process.env.HUMANET_GENERAL_CONSULTATION_MINUTES ?? 60);
  if (!Number.isFinite(value)) return 60;
  return Math.min(240, Math.max(15, Math.round(value)));
}

export function getEventSlugFromCalUrl(value: string | null): string | null {
  if (!value) return null;

  try {
    const url = new URL(value);
    const parts = url.pathname.split("/").filter(Boolean);
    return parts.at(-1)?.trim() || null;
  } catch {
    return null;
  }
}

export function getConfiguredCalComEventSlugs() {
  const report = getEventSlugFromCalUrl(
    clean(process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL),
  );
  const decision = getEventSlugFromCalUrl(
    clean(process.env.NEXT_PUBLIC_CALCOM_DECISION_90_URL),
  );
  const standalone = getEventSlugFromCalUrl(
    clean(process.env.NEXT_PUBLIC_CALCOM_GENERAL_CONSULTATION_URL) ??
      clean(process.env.NEXT_PUBLIC_CALCOM_REPORT_60_URL),
  );

  return { report, decision, standalone };
}

export function getCalComIntegrationStatus() {
  return {
    webhookConfigured: Boolean(clean(process.env.CALCOM_WEBHOOK_SECRET)),
    apiSyncConfigured: Boolean(clean(process.env.CALCOM_API_KEY)),
  };
}
