// @generated by install-humanet-values-consultations-v5.mjs
import "server-only";

import { desc, eq, or } from "drizzle-orm";

import { consultationEntitlements, users } from "@/drizzle/schema";
import { requireSession } from "@/server/auth/require-session";
import { controlDb } from "@/server/db/control-db";
import {
  chooseConsultationEntitlementForBooking,
  type ConsultationBookingCandidate,
} from "./consultation-booking-match";
import {
  getConfiguredCalComEventSlugs,
  getStandaloneConsultationMinutes,
} from "./calcom-config.server";

type BookingBucket = "upcoming" | "past" | "cancelled";

type NormalizedBooking = {
  uid: string;
  start: Date | null;
  end: Date | null;
  createdAt: Date | null;
  durationMinutes: number | null;
  eventSlug: string | null;
  meetingUrl: string | null;
  attendeeEmail: string | null;
  metadata: Record<string, unknown>;
  bucket: BookingBucket;
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function text(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function date(value: unknown): Date | null {
  const raw = text(value);
  if (!raw) return null;
  const result = new Date(raw);
  return Number.isNaN(result.getTime()) ? null : result;
}

function attendeeEmail(value: unknown): string | null {
  if (!Array.isArray(value)) return null;
  for (const item of value) {
    const email = text(asRecord(item).email)?.toLowerCase();
    if (email) return email;
  }
  return null;
}

function normalizeBooking(value: unknown, bucket: BookingBucket): NormalizedBooking | null {
  const row = asRecord(value);
  const uid = text(row.uid);
  if (!uid) return null;

  const eventType = asRecord(row.eventType);
  const duration = Number(row.duration);

  return {
    uid,
    start: date(row.start),
    end: date(row.end),
    createdAt: date(row.createdAt),
    durationMinutes: Number.isFinite(duration) && duration > 0 ? duration : null,
    eventSlug: text(eventType.slug),
    meetingUrl: text(row.meetingUrl) ?? text(row.location),
    attendeeEmail: attendeeEmail(row.attendees),
    metadata: asRecord(row.metadata),
    bucket,
  };
}

async function fetchBookingsForEmail(email: string): Promise<NormalizedBooking[]> {
  const apiKey = process.env.CALCOM_API_KEY?.trim();
  if (!apiKey) return [];

  const buckets: BookingBucket[] = ["upcoming", "past", "cancelled"];
  const results = await Promise.all(
    buckets.map(async (bucket) => {
      const url = new URL("https://api.cal.com/v2/bookings");
      url.searchParams.set("status", bucket);
      url.searchParams.set("attendeeEmail", email);
      url.searchParams.set("limit", "100");

      const response = await fetch(url, {
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "cal-api-version": "2026-05-01",
        },
        cache: "no-store",
      });

      if (!response.ok) {
        console.error("CALCOM_API_BOOKINGS_FETCH_FAILED", {
          bucket,
          status: response.status,
        });
        return [] as NormalizedBooking[];
      }

      const body = asRecord(await response.json());
      const data = Array.isArray(body.data) ? body.data : [];
      return data
        .map((item) => normalizeBooking(item, bucket))
        .filter((item): item is NormalizedBooking => Boolean(item));
    }),
  );

  return results.flat();
}

function kindHintForSlug(slug: string | null) {
  if (!slug) return null;
  const configured = getConfiguredCalComEventSlugs();

  if (configured.decision && slug === configured.decision) {
    return "decision_support" as const;
  }

  if (
    configured.report &&
    slug === configured.report &&
    configured.standalone !== configured.report
  ) {
    return "report_consultation" as const;
  }

  if (
    configured.standalone &&
    slug === configured.standalone &&
    configured.standalone !== configured.report
  ) {
    return "standalone" as const;
  }

  return null;
}

function sourceHintForKind(kind: ReturnType<typeof kindHintForSlug>) {
  if (kind === "standalone") return "standalone" as const;
  if (kind === "decision_support" || kind === "report_consultation") {
    return "package" as const;
  }
  return null;
}

function isConfiguredEventSlug(slug: string | null): boolean {
  if (!slug) return false;
  const configured = getConfiguredCalComEventSlugs();
  return [configured.report, configured.decision, configured.standalone]
    .filter(Boolean)
    .includes(slug);
}

function localCandidate(row: typeof consultationEntitlements.$inferSelect): ConsultationBookingCandidate {
  return {
    id: row.id,
    source: row.source,
    kind: row.kind,
    durationMinutes: row.durationMinutes,
    status: row.status,
    bookingReference: row.bookingReference,
    createdAt: row.createdAt,
    bookingMetadata: row.bookingMetadata,
  };
}

async function applyBooking(
  entitlement: typeof consultationEntitlements.$inferSelect,
  booking: NormalizedBooking,
) {
  const now = new Date();

  if (booking.bucket === "cancelled") {
    if (entitlement.bookingReference !== booking.uid) return false;

    const restorePackage = entitlement.source === "package";
    await controlDb
      .update(consultationEntitlements)
      .set({
        status: restorePackage ? "available" : "cancelled",
        scheduledStartAt: restorePackage ? null : booking.start,
        scheduledEndAt: restorePackage ? null : booking.end,
        meetingUrl: restorePackage ? null : entitlement.meetingUrl,
        cancelledAt: now,
        bookingMetadata: {
          ...asRecord(entitlement.bookingMetadata),
          calcomApiSyncAt: now.toISOString(),
          lastCancelledBookingUid: booking.uid,
        },
        updatedAt: now,
      })
      .where(eq(consultationEntitlements.id, entitlement.id));
    return true;
  }

  const status = booking.bucket === "past" ? "completed" : "booked";
  const minutes =
    booking.start && booking.end
      ? Math.round((booking.end.getTime() - booking.start.getTime()) / 60_000)
      : null;

  await controlDb
    .update(consultationEntitlements)
    .set({
      status,
      bookingReference: booking.uid,
      scheduledStartAt: booking.start,
      scheduledEndAt: booking.end,
      meetingUrl: booking.meetingUrl ?? entitlement.meetingUrl,
      durationMinutes:
        minutes && minutes > 0
          ? Math.min(480, minutes)
          : booking.durationMinutes ?? entitlement.durationMinutes,
      bookedAt: entitlement.bookedAt ?? booking.createdAt ?? now,
      completedAt: status === "completed" ? entitlement.completedAt ?? now : null,
      cancelledAt: null,
      bookingMetadata: {
        ...asRecord(entitlement.bookingMetadata),
        ...booking.metadata,
        calcomApiSyncAt: now.toISOString(),
        eventSlug: booking.eventSlug,
      },
      updatedAt: now,
    })
    .where(eq(consultationEntitlements.id, entitlement.id));

  return true;
}

export async function reconcileCalComBookingsForUser({
  userId,
  email,
}: {
  userId: string;
  email: string;
}) {
  if (!process.env.CALCOM_API_KEY?.trim()) {
    return { configured: false as const, updated: 0, created: 0 };
  }

  const bookings = (await fetchBookingsForEmail(email.toLowerCase()))
    .filter((booking) => isConfiguredEventSlug(booking.eventSlug))
    .sort((a, b) => {
      const bucketRank = { upcoming: 0, past: 1, cancelled: 2 } as const;
      const rank = bucketRank[a.bucket] - bucketRank[b.bucket];
      if (rank !== 0) return rank;
      return (a.createdAt?.getTime() ?? 0) - (b.createdAt?.getTime() ?? 0);
    });

  const entitlements = await controlDb
    .select()
    .from(consultationEntitlements)
    .where(eq(consultationEntitlements.userId, userId))
    .orderBy(desc(consultationEntitlements.createdAt));

  let updated = 0;
  let created = 0;

  for (const booking of bookings) {
    let entitlement = entitlements.find(
      (item) => item.bookingReference === booking.uid,
    );

    const kindHint = kindHintForSlug(booking.eventSlug);

    if (!entitlement && booking.bucket !== "cancelled") {
      const selected = chooseConsultationEntitlementForBooking(
        entitlements.map(localCandidate),
        {
          uid: booking.uid,
          durationMinutes: booking.durationMinutes,
          createdAt: booking.createdAt,
          kindHint,
          sourceHint: sourceHintForKind(kindHint),
        },
      );
      entitlement = selected
        ? entitlements.find((item) => item.id === selected.id)
        : undefined;
    }

    const configuredSlugs = getConfiguredCalComEventSlugs();
    const canRecoverAsStandalone =
      Boolean(booking.eventSlug) &&
      configuredSlugs.standalone === booking.eventSlug;

    if (!entitlement && canRecoverAsStandalone && booking.bucket !== "cancelled") {
      const now = new Date();
      const [newRow] = await controlDb
        .insert(consultationEntitlements)
        .values({
          orderId: null,
          userId,
          source: "standalone",
          kind: "standalone",
          durationMinutes:
            booking.durationMinutes ?? getStandaloneConsultationMinutes(),
          status: "available",
          bookingProvider: "calcom",
          bookingMetadata: { recoveredFromCalComApi: true },
          createdAt: booking.createdAt ?? now,
          updatedAt: now,
        })
        .returning();
      entitlements.push(newRow);
      entitlement = newRow;
      created += 1;
    }

    if (!entitlement) continue;

    if (await applyBooking(entitlement, booking)) {
      const index = entitlements.findIndex((item) => item.id === entitlement?.id);
      if (index >= 0) {
        entitlements[index] = {
          ...entitlements[index],
          status:
            booking.bucket === "cancelled"
              ? entitlements[index].source === "package"
                ? "available"
                : "cancelled"
              : booking.bucket === "past"
                ? "completed"
                : "booked",
          bookingReference:
            booking.bucket === "cancelled"
              ? entitlements[index].bookingReference
              : booking.uid,
          scheduledStartAt:
            booking.bucket === "cancelled" && entitlements[index].source === "package"
              ? null
              : booking.start,
        };
      }
      updated += 1;
    }
  }

  return { configured: true as const, updated, created };
}

export async function reconcileCurrentUserCalComBookings() {
  const session = await requireSession();
  if (!session.user.email) {
    return { configured: Boolean(process.env.CALCOM_API_KEY?.trim()), updated: 0, created: 0 };
  }

  return reconcileCalComBookingsForUser({
    userId: session.user.id,
    email: session.user.email,
  });
}

export async function reconcilePendingCalComBookingsAdmin() {
  if (!process.env.CALCOM_API_KEY?.trim()) {
    return { configured: false as const, users: 0, updated: 0, created: 0 };
  }

  const rows = await controlDb
    .select({
      userId: users.id,
      email: users.email,
    })
    .from(consultationEntitlements)
    .innerJoin(users, eq(users.id, consultationEntitlements.userId))
    .where(
      or(
        eq(consultationEntitlements.status, "available"),
        eq(consultationEntitlements.status, "booked"),
      ),
    )
    .orderBy(desc(consultationEntitlements.updatedAt))
    .limit(200);

  const unique = new Map<string, string>();
  for (const row of rows) {
    if (row.email) unique.set(row.userId, row.email);
  }

  let updated = 0;
  let created = 0;

  for (const [userId, email] of unique) {
    const result = await reconcileCalComBookingsForUser({ userId, email });
    updated += result.updated;
    created += result.created;
  }

  return {
    configured: true as const,
    users: unique.size,
    updated,
    created,
  };
}
