// @generated by install-humanet-values-marketing.mjs
function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function optionalString(
  record: Record<string, unknown>,
  key: string,
): string | null {
  const value = record[key];
  return typeof value === "string" && value.trim()
    ? value.trim()
    : null;
}

export type ConsultationReportReference = {
  tenantSlug: string;
  assessmentSessionId: string;
  reportTemplateVersionId: string;
  projectQuestionnaireId: string | null;
  questionnaireVersionId: string | null;
};

export function readConsultationReportReference(
  orderMetadata: unknown,
): ConsultationReportReference | null {
  const metadata = asRecord(orderMetadata);
  const tenantSlug = optionalString(metadata, "tenantSlug");
  const assessmentSessionId = optionalString(
    metadata,
    "assessmentSessionId",
  );
  const reportTemplateVersionId = optionalString(
    metadata,
    "reportTemplateVersionId",
  );

  if (!tenantSlug || !assessmentSessionId || !reportTemplateVersionId) {
    return null;
  }

  return {
    tenantSlug,
    assessmentSessionId,
    reportTemplateVersionId,
    projectQuestionnaireId: optionalString(
      metadata,
      "projectQuestionnaireId",
    ),
    questionnaireVersionId: optionalString(
      metadata,
      "questionnaireVersionId",
    ),
  };
}

function appendScope(
  pathname: string,
  reference: ConsultationReportReference,
): string {
  const params = new URLSearchParams();

  if (reference.projectQuestionnaireId) {
    params.set(
      "projectQuestionnaireId",
      reference.projectQuestionnaireId,
    );
  }

  if (reference.questionnaireVersionId) {
    params.set(
      "questionnaireVersionId",
      reference.questionnaireVersionId,
    );
  }

  const query = params.toString();
  return query ? `${pathname}?${query}` : pathname;
}

export function buildMyConsultationReportHref(
  orderMetadata: unknown,
): string | null {
  const reference = readConsultationReportReference(orderMetadata);
  if (!reference) return null;

  return appendScope(
    `/my/assessment/sessions/${reference.assessmentSessionId}` +
      `/report/${reference.reportTemplateVersionId}`,
    reference,
  );
}

export function buildAdminConsultationReportHref(
  orderMetadata: unknown,
): string | null {
  const reference = readConsultationReportReference(orderMetadata);
  if (!reference) return null;

  return appendScope(
    `/t/${encodeURIComponent(reference.tenantSlug)}` +
      `/assessment-sessions/${reference.assessmentSessionId}` +
      `/report/${reference.reportTemplateVersionId}`,
    reference,
  );
}
