// @generated by install-humanet-values-consultations-v5.mjs
import { describe, expect, it } from "vitest";

import { chooseConsultationEntitlementForBooking } from "./consultation-booking-match";

const base = {
  source: "package",
  kind: "report_consultation",
  durationMinutes: 60,
  status: "available",
  bookingReference: null,
  createdAt: new Date("2026-08-01T10:00:00Z"),
  bookingMetadata: {},
};

describe("chooseConsultationEntitlementForBooking", () => {
  it("prefers exact booking reference", () => {
    const result = chooseConsultationEntitlementForBooking(
      [
        { ...base, id: "a", bookingReference: "other", status: "booked" },
        { ...base, id: "b", bookingReference: "uid-1", status: "booked" },
      ],
      {
        uid: "uid-1",
        durationMinutes: 60,
        createdAt: new Date("2026-08-02T10:00:00Z"),
        sourceHint: null,
        kindHint: null,
      },
    );

    expect(result?.id).toBe("b");
  });

  it("uses recent booking handoff for fallback matching", () => {
    const result = chooseConsultationEntitlementForBooking(
      [
        { ...base, id: "old" },
        {
          ...base,
          id: "opened",
          bookingMetadata: { bookingOpenedAt: "2026-08-02T09:55:00Z" },
        },
      ],
      {
        uid: "uid-2",
        durationMinutes: 60,
        createdAt: new Date("2026-08-02T10:00:00Z"),
        sourceHint: "package",
        kindHint: "report_consultation",
      },
    );

    expect(result?.id).toBe("opened");
  });
});
