// @generated by install-humanet-values-consultations-v5.mjs
export type ConsultationBookingCandidate = {
  id: string;
  source: string;
  kind: string;
  durationMinutes: number;
  status: string;
  bookingReference: string | null;
  createdAt: Date;
  bookingMetadata: unknown;
};

export type ConsultationBookingDescriptor = {
  uid: string;
  durationMinutes: number | null;
  createdAt: Date | null;
  sourceHint: "package" | "standalone" | null;
  kindHint: "report_consultation" | "decision_support" | "standalone" | null;
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function handoffAt(value: unknown): number {
  const record = asRecord(value);
  const raw = record.bookingOpenedAt;
  if (typeof raw !== "string") return 0;
  const time = new Date(raw).getTime();
  return Number.isFinite(time) ? time : 0;
}

function candidateScore(
  candidate: ConsultationBookingCandidate,
  booking: ConsultationBookingDescriptor,
): number {
  if (candidate.bookingReference === booking.uid) return 10_000;

  if (candidate.status === "booked" && candidate.bookingReference) {
    return -1;
  }

  let score = 0;

  if (candidate.status === "available") score += 50;
  if (booking.sourceHint && candidate.source === booking.sourceHint) score += 100;
  if (booking.kindHint && candidate.kind === booking.kindHint) score += 100;

  if (
    booking.durationMinutes &&
    Math.abs(candidate.durationMinutes - booking.durationMinutes) <= 5
  ) {
    score += 80;
  }

  const opened = handoffAt(candidate.bookingMetadata);
  if (opened > 0) {
    score += 300;

    if (booking.createdAt) {
      const delta = booking.createdAt.getTime() - opened;
      if (delta >= -5 * 60_000 && delta <= 24 * 60 * 60_000) {
        score += 200;
      }
    }
  }

  if (booking.createdAt) {
    const createdDelta = booking.createdAt.getTime() - candidate.createdAt.getTime();
    if (createdDelta >= -5 * 60_000) score += 20;
  }

  return score;
}

export function chooseConsultationEntitlementForBooking(
  candidates: ConsultationBookingCandidate[],
  booking: ConsultationBookingDescriptor,
): ConsultationBookingCandidate | null {
  const exact = candidates.find(
    (candidate) => candidate.bookingReference === booking.uid,
  );
  if (exact) return exact;

  const eligible = candidates.filter((candidate) => {
    if (candidate.status !== "available" && candidate.status !== "booked") {
      return false;
    }

    if (candidate.status === "booked" && candidate.bookingReference) {
      return false;
    }

    if (booking.sourceHint && candidate.source !== booking.sourceHint) {
      return false;
    }

    if (booking.kindHint && candidate.kind !== booking.kindHint) {
      return false;
    }

    return true;
  });

  const scored = eligible
    .map((candidate) => ({
      candidate,
      score: candidateScore(candidate, booking),
    }))
    .filter((item) => item.score >= 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return b.candidate.createdAt.getTime() - a.candidate.createdAt.getTime();
    });

  if (scored.length === 0) return null;
  if (scored.length === 1) return scored[0].candidate;

  const first = scored[0];
  const second = scored[1];

  if (first.score >= 300 || first.score - second.score >= 80) {
    return first.candidate;
  }

  return null;
}
