// @generated by install-humanet-values-marketing.mjs
"use client";

// @humanet-consent-post-login-sync-v1
// @humanet-consent-react-effect-lint-fix-v1.1

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import { Settings2, X } from "lucide-react";
import { usePathname } from "next/navigation";

import { Button } from "@/components/ui/button";
import {
  readConsentCookie,
  removeKnownAnalyticsCookies,
  writeConsentCookie,
} from "../lib/consent-cookie";
import {
  HUMANET_CONSENT_EVENT_NAME,
  createDefaultConsentState,
  type ConsentState,
} from "../types/consent.types";

type ConsentContextValue = {
  consent: ConsentState;
  hasDecision: boolean;
  hydrated: boolean;
  settingsOpen: boolean;
  openSettings: () => void;
  closeSettings: () => void;
  saveConsent: (input: Pick<ConsentState, "analytics" | "marketing">) => void;
};

const consentVersion =
  process.env.NEXT_PUBLIC_CONSENT_VERSION?.trim() || "2026-08-01";

const ConsentContext = createContext<ConsentContextValue | null>(null);

export function useConsent(): ConsentContextValue {
  const value = useContext(ConsentContext);

  if (!value) {
    throw new Error("useConsent must be used inside ConsentProvider.");
  }

  return value;
}

type ConsentPersistenceSource = "cookie_banner" | "post_login_sync";

async function persistConsentForAuthenticatedUser(
  state: ConsentState,
  source: ConsentPersistenceSource,
): Promise<boolean> {
  try {
    const response = await fetch("/api/privacy/consent", {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({ ...state, source }),
      keepalive: true,
    });

    if (!response.ok) return false;

    const payload = (await response.json().catch(() => null)) as
      | { persisted?: boolean }
      | null;

    return payload?.persisted === true;
  } catch {
    // Cookie remains the browser source of truth. Server persistence is best effort.
    return false;
  }
}

export function ConsentProvider({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  // @humanet-hide-consent-on-print-v1
  // Route groups such as (print) do not isolate us from the root layout.
  // Hide only the consent UI when the public URL contains a /print segment.
  const isPrintRoute = pathname
    .split("/")
    .filter(Boolean)
    .includes("print");

  const [consent, setConsent] = useState<ConsentState>(() =>
    createDefaultConsentState(consentVersion),
  );
  const [hasDecision, setHasDecision] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);

  useEffect(() => {
    const existing = readConsentCookie(consentVersion);
    let cancelled = false;

    // Cookie is an external browser source. Defer React state synchronization
    // to a microtask instead of synchronously setting state in the effect body.
    queueMicrotask(() => {
      if (cancelled) return;

      if (existing) {
        setConsent(existing);
        setHasDecision(true);
      }

      setHydrated(true);
    });

    return () => {
      cancelled = true;
    };
  }, []);

  // Jeśli decyzja cookie została podjęta przed logowaniem, pierwszy zapis do
  // /api/privacy/consent nie ma userId i zwraca persisted=false.
  // Po logowaniu RootLayout/ConsentProvider uruchamia się ponownie i ten efekt
  // synchronizuje tę samą decyzję do consent_records. Sukces zapamiętujemy
  // per-tab, żeby nie wykonywać zbędnych requestów przy każdej nawigacji.
  useEffect(() => {
    if (!hydrated || !hasDecision) return;

    const syncKey =
      `humanet-consent-synced:${consent.version}:${consent.updatedAt}`;

    if (window.sessionStorage.getItem(syncKey) === "1") return;

    let cancelled = false;

    void persistConsentForAuthenticatedUser(consent, "post_login_sync").then(
      (persisted) => {
        if (!cancelled && persisted) {
          window.sessionStorage.setItem(syncKey, "1");
        }
      },
    );

    return () => {
      cancelled = true;
    };
  }, [consent, hasDecision, hydrated, pathname]);

  const saveConsent = useCallback(
    (input: Pick<ConsentState, "analytics" | "marketing">) => {
      const nextState: ConsentState = {
        necessary: true,
        analytics: input.analytics,
        marketing: input.marketing,
        version: consentVersion,
        updatedAt: new Date().toISOString(),
      };

      writeConsentCookie(nextState);
      setConsent(nextState);
      setHasDecision(true);
      setSettingsOpen(false);

      if (!nextState.analytics) {
        removeKnownAnalyticsCookies();
      }

      window.dispatchEvent(
        new CustomEvent(HUMANET_CONSENT_EVENT_NAME, {
          detail: nextState,
        }),
      );

      void persistConsentForAuthenticatedUser(nextState, "cookie_banner");
    },
    [],
  );

  const value = useMemo<ConsentContextValue>(
    () => ({
      consent,
      hasDecision,
      hydrated,
      settingsOpen,
      openSettings: () => setSettingsOpen(true),
      closeSettings: () => setSettingsOpen(false),
      saveConsent,
    }),
    [consent, hasDecision, hydrated, settingsOpen, saveConsent],
  );

  return (
    <ConsentContext.Provider value={value}>
      {children}
      {!isPrintRoute ? (
        <>
          <ConsentBanner />
          <ConsentSettingsButton />
          <ConsentSettingsDialog />
        </>
      ) : null}
    </ConsentContext.Provider>
  );
}

function ConsentBanner() {
  const { hydrated, hasDecision, saveConsent, openSettings } = useConsent();

  if (!hydrated || hasDecision) return null;

  return (
    <section
      aria-label="Ustawienia plików cookie"
      className="fixed inset-x-3 bottom-3 z-[100] mx-auto max-w-4xl rounded-2xl border border-black/10 bg-white p-5 shadow-2xl sm:p-6"
    >
      <h2 className="text-lg font-semibold tracking-tight">
        Prywatność i pliki cookie
      </h2>
      <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">
        Niezbędne pliki cookie zapewniają logowanie, bezpieczeństwo, płatności
        i pamięć rozpoczętego procesu. Analitykę uruchamiamy wyłącznie po Twojej
        zgodzie. Ten sam wybór obowiązuje na humanet.me i values.humanet.me.
      </p>
      <a
        href="/legal/polityka-prywatnosci"
        target="_blank"
        rel="noreferrer"
        className="mt-2 inline-block text-sm font-medium underline underline-offset-4"
      >
        Polityka prywatności
      </a>

      <div className="mt-5 grid gap-2 sm:grid-cols-3">
        <Button
          type="button"
          onClick={() => saveConsent({ analytics: true, marketing: true })}
        >
          Akceptuję wszystkie
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={() => saveConsent({ analytics: false, marketing: false })}
        >
          Odrzucam opcjonalne
        </Button>
        <Button type="button" variant="ghost" onClick={openSettings}>
          Dostosuj
        </Button>
      </div>
    </section>
  );
}

function ConsentSettingsButton() {
  const { hydrated, hasDecision, openSettings } = useConsent();

  if (!hydrated || !hasDecision) return null;

  return (
    <button
      type="button"
      onClick={openSettings}
      className="fixed bottom-4 left-4 z-[90] inline-flex h-10 items-center gap-2 rounded-full border border-black/10 bg-white px-3 text-xs font-semibold shadow-lg transition hover:bg-neutral-50"
      aria-label="Zmień ustawienia prywatności"
    >
      <Settings2 className="h-4 w-4" />
      Prywatność
    </button>
  );
}

function ConsentSettingsDialog() {
  const { settingsOpen, closeSettings, consent, saveConsent } = useConsent();
  const [analytics, setAnalytics] = useState(consent.analytics);
  const [marketing, setMarketing] = useState(consent.marketing);

  useEffect(() => {
    if (!settingsOpen) return;

    let cancelled = false;

    // Synchronize the local draft after the dialog is opened, but avoid
    // synchronous setState calls in the effect body.
    queueMicrotask(() => {
      if (cancelled) return;
      setAnalytics(consent.analytics);
      setMarketing(consent.marketing);
    });

    return () => {
      cancelled = true;
    };
  }, [settingsOpen, consent.analytics, consent.marketing]);

  if (!settingsOpen) return null;

  return (
    <div
      className="fixed inset-0 z-[110] flex items-center justify-center bg-black/40 p-4"
      role="dialog"
      aria-modal="true"
      aria-labelledby="consent-settings-title"
    >
      <div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 id="consent-settings-title" className="text-xl font-semibold">
              Ustawienia prywatności
            </h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              Zgody opcjonalne możesz w każdej chwili zmienić lub wycofać.
            </p>
            <a
              href="/legal/polityka-prywatnosci"
              target="_blank"
              rel="noreferrer"
              className="mt-2 inline-block text-sm font-medium underline underline-offset-4"
            >
              Zobacz Politykę prywatności
            </a>
          </div>
          <button
            type="button"
            onClick={closeSettings}
            className="rounded-full p-2 hover:bg-neutral-100"
            aria-label="Zamknij"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="mt-6 space-y-3">
          <ConsentToggle
            label="Niezbędne"
            description="Zapewniają bezpieczne logowanie, płatności i zapamiętanie Twoich ustawień."
            checked
            disabled
            onChange={() => undefined}
          />
          <ConsentToggle
            label="Analityczne"
            description="Pomagają nam zrozumieć, jak korzystasz z HUMANET, dzięki czemu możemy ulepszać serwis i przebieg badania."
            checked={analytics}
            onChange={setAnalytics}
          />
          <ConsentToggle
            label="Marketingowe"
            description="Pomagają mierzyć skuteczność naszych działań promocyjnych i lepiej dopasowywać komunikację. Możesz je wyłączyć w każdej chwili."
            checked={marketing}
            onChange={setMarketing}
          />
        </div>

        <div className="mt-6 flex flex-wrap justify-end gap-2">
          <Button type="button" variant="ghost" onClick={closeSettings}>
            Anuluj
          </Button>
          <Button
            type="button"
            onClick={() => saveConsent({ analytics, marketing })}
          >
            Zapisz ustawienia
          </Button>
        </div>
      </div>
    </div>
  );
}

function ConsentToggle({
  label,
  description,
  checked,
  disabled = false,
  onChange,
}: {
  label: string;
  description: string;
  checked: boolean;
  disabled?: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <label className="flex items-start justify-between gap-4 rounded-xl border p-4">
      <span>
        <span className="block font-medium">{label}</span>
        <span className="mt-1 block text-xs leading-5 text-muted-foreground">
          {description}
        </span>
      </span>
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={(event) => onChange(event.currentTarget.checked)}
        className="mt-1 h-5 w-5 accent-teal-700"
      />
    </label>
  );
}
