// @generated by install-humanet-values-marketing.mjs
"use client";

import { useEffect, useRef, useState } from "react";
import Script from "next/script";
import { usePathname, useSearchParams } from "next/navigation";

import { useConsent } from "./consent-provider";
import { HUMANET_CONSENT_EVENT_NAME } from "../types/consent.types";

declare global {
  interface Window {
    dataLayer?: Array<Record<string, unknown> | unknown[]>;
    gtag?: (...args: unknown[]) => void;
    clarity?: (...args: unknown[]) => void;
  }
}

const gtmId = process.env.NEXT_PUBLIC_GTM_ID?.trim();
const gaMeasurementId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID?.trim();
const clarityProjectId = process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID?.trim();

function initializeConsentDefaults() {
  window.dataLayer = window.dataLayer || [];
  window.gtag =
    window.gtag ||
    function gtag(...args: unknown[]) {
      window.dataLayer?.push(args);
    };

  window.gtag("consent", "default", {
    analytics_storage: "denied",
    ad_storage: "denied",
    ad_user_data: "denied",
    ad_personalization: "denied",
    functionality_storage: "granted",
    security_storage: "granted",
  });
}

export function DynamicAnalytics() {
  const { consent, hydrated } = useConsent();
  const [enabled, setEnabled] = useState(false);
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const lastPageView = useRef<string | null>(null);

  useEffect(() => {
    initializeConsentDefaults();
    setEnabled(hydrated && consent.analytics);

    window.gtag?.("consent", "update", {
      analytics_storage: consent.analytics ? "granted" : "denied",
      ad_storage: "denied",
      ad_user_data: "denied",
      ad_personalization: "denied",
    });

    const onConsentChanged = () => {
      setEnabled(consent.analytics);
    };

    window.addEventListener(HUMANET_CONSENT_EVENT_NAME, onConsentChanged);
    return () =>
      window.removeEventListener(HUMANET_CONSENT_EVENT_NAME, onConsentChanged);
  }, [hydrated, consent.analytics]);

  useEffect(() => {
    if (!enabled || (!gtmId && !gaMeasurementId)) return;

    const query = searchParams.toString();
    const pagePath = query ? `${pathname}?${query}` : pathname;

    if (lastPageView.current === pagePath) return;
    lastPageView.current = pagePath;

    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({
      event: "page_view",
      page_path: pagePath,
    });
  }, [enabled, pathname, searchParams]);

  if (process.env.NODE_ENV !== "production" || !enabled) return null;

  return (
    <>
      {gtmId ? (
        <Script
          id="humanet-gtm-script"
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtm.js?id=${encodeURIComponent(gtmId)}`}
          onLoad={() => {
            window.dataLayer = window.dataLayer || [];
            window.dataLayer.push({
              "gtm.start": Date.now(),
              event: "gtm.js",
            });
          }}
        />
      ) : gaMeasurementId ? (
        <>
          <Script
            id="humanet-ga4-script"
            strategy="afterInteractive"
            src={`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(
              gaMeasurementId,
            )}`}
          />
          <Script id="humanet-ga4-config" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              window.gtag = window.gtag || function(){window.dataLayer.push(arguments);};
              window.gtag("js", new Date());
              window.gtag("config", "${gaMeasurementId}", { send_page_view: false });
            `}
          </Script>
        </>
      ) : null}

      {clarityProjectId ? (
        <Script id="humanet-clarity-script" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${clarityProjectId}");
            window.clarity("consentv2", {
              ad_Storage: "denied",
              analytics_Storage: "granted"
            });
          `}
        </Script>
      ) : null}
    </>
  );
}
