// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { desc, eq } from "drizzle-orm";

import {
  consultationEntitlements,
  reportAccessOrders,
  users,
} from "@/drizzle/schema";
import { requireSuperAdmin } from "@/server/auth/require-super-admin";
import { controlDb } from "@/server/db/control-db";

export async function listConsultationEntitlementsAdmin() {
  await requireSuperAdmin();

  return controlDb
    .select({
      id: consultationEntitlements.id,
      orderId: consultationEntitlements.orderId,
      userId: consultationEntitlements.userId,
      userEmail: users.email,
      source: consultationEntitlements.source,
      kind: consultationEntitlements.kind,
      durationMinutes: consultationEntitlements.durationMinutes,
      status: consultationEntitlements.status,
      bookingProvider: consultationEntitlements.bookingProvider,
      bookingReference: consultationEntitlements.bookingReference,
      scheduledStartAt: consultationEntitlements.scheduledStartAt,
      scheduledEndAt: consultationEntitlements.scheduledEndAt,
      meetingUrl: consultationEntitlements.meetingUrl,
      rescheduleUrl: consultationEntitlements.rescheduleUrl,
      cancelUrl: consultationEntitlements.cancelUrl,
      createdAt: consultationEntitlements.createdAt,
      bookedAt: consultationEntitlements.bookedAt,
      completedAt: consultationEntitlements.completedAt,
      orderStatus: reportAccessOrders.status,
      orderMetadata: reportAccessOrders.metadata,
    })
    .from(consultationEntitlements)
    .innerJoin(users, eq(users.id, consultationEntitlements.userId))
    .leftJoin(
      reportAccessOrders,
      eq(reportAccessOrders.id, consultationEntitlements.orderId),
    )
    .orderBy(
      desc(consultationEntitlements.scheduledStartAt),
      desc(consultationEntitlements.createdAt),
    );
}
