// @generated by install-humanet-values-consultations-v5.mjs
import "server-only";

import { and, desc, eq } from "drizzle-orm";

import { consultationEntitlements } from "@/drizzle/schema";
import { requireSession } from "@/server/auth/require-session";
import { controlDb } from "@/server/db/control-db";
import {
  getCalComBookingUrlForKind,
  getStandaloneConsultationMinutes,
} from "../lib/calcom-config.server";

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function safeDate(value: unknown): Date | null {
  if (typeof value !== "string" || !value.trim()) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function safeString(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export async function createOrResumeStandaloneConsultationForCurrentUser() {
  const session = await requireSession();
  const bookingUrl = getCalComBookingUrlForKind("standalone");

  if (!bookingUrl) {
    throw new Error(
      "Brakuje NEXT_PUBLIC_CALCOM_GENERAL_CONSULTATION_URL albo NEXT_PUBLIC_CALCOM_REPORT_60_URL.",
    );
  }

  const existing = await controlDb.query.consultationEntitlements.findFirst({
    where: and(
      eq(consultationEntitlements.userId, session.user.id),
      eq(consultationEntitlements.source, "standalone"),
      eq(consultationEntitlements.status, "available"),
    ),
    orderBy: [desc(consultationEntitlements.createdAt)],
  });

  if (existing && !existing.bookingReference) {
    return {
      entitlement: existing,
      bookingUrl,
      user: {
        email: session.user.email ?? null,
        name: session.user.name ?? null,
      },
    };
  }

  const now = new Date();
  const [created] = await controlDb
    .insert(consultationEntitlements)
    .values({
      orderId: null,
      userId: session.user.id,
      source: "standalone",
      kind: "standalone",
      durationMinutes: getStandaloneConsultationMinutes(),
      status: "available",
      bookingProvider: "calcom",
      bookingMetadata: {
        createdFrom: "my_consultations",
      },
      createdAt: now,
      updatedAt: now,
    })
    .returning();

  return {
    entitlement: created,
    bookingUrl,
    user: {
      email: session.user.email ?? null,
      name: session.user.name ?? null,
    },
  };
}

export async function markOwnedConsultationBookingOpened({
  entitlementId,
  surface,
}: {
  entitlementId: string;
  surface: string | null;
}) {
  const session = await requireSession();
  const existing = await controlDb.query.consultationEntitlements.findFirst({
    where: and(
      eq(consultationEntitlements.id, entitlementId),
      eq(consultationEntitlements.userId, session.user.id),
    ),
  });

  if (!existing) throw new Error("Nie znaleziono konsultacji.");

  const now = new Date();
  await controlDb
    .update(consultationEntitlements)
    .set({
      bookingMetadata: {
        ...asRecord(existing.bookingMetadata),
        bookingOpenedAt: now.toISOString(),
        bookingSurface: surface,
      },
      updatedAt: now,
    })
    .where(eq(consultationEntitlements.id, existing.id));

  return existing;
}

export async function completeOwnedConsultationBooking(input: {
  entitlementId: string;
  uid: unknown;
  startTime: unknown;
  endTime: unknown;
  videoCallUrl: unknown;
  eventTypeId: unknown;
  eventStatus: unknown;
}) {
  const session = await requireSession();
  const existing = await controlDb.query.consultationEntitlements.findFirst({
    where: and(
      eq(consultationEntitlements.id, input.entitlementId),
      eq(consultationEntitlements.userId, session.user.id),
    ),
  });

  if (!existing) throw new Error("Nie znaleziono konsultacji.");

  const uid = safeString(input.uid);
  const start = safeDate(input.startTime);
  const end = safeDate(input.endTime);

  if (!uid || !start || !end) {
    throw new Error("Cal.com nie przekazał kompletnych danych rezerwacji.");
  }

  const minutes = Math.round((end.getTime() - start.getTime()) / 60_000);
  const durationMinutes =
    Number.isFinite(minutes) && minutes > 0
      ? Math.min(480, minutes)
      : existing.durationMinutes;

  const now = new Date();
  await controlDb
    .update(consultationEntitlements)
    .set({
      status: "booked",
      bookingReference: uid,
      scheduledStartAt: start,
      scheduledEndAt: end,
      meetingUrl: safeString(input.videoCallUrl) ?? existing.meetingUrl,
      durationMinutes,
      bookedAt: existing.bookedAt ?? now,
      cancelledAt: null,
      bookingMetadata: {
        ...asRecord(existing.bookingMetadata),
        clientCallbackAt: now.toISOString(),
        eventTypeId:
          typeof input.eventTypeId === "number" ? input.eventTypeId : null,
        eventStatus: safeString(input.eventStatus),
      },
      updatedAt: now,
    })
    .where(eq(consultationEntitlements.id, existing.id));

  return { ok: true as const };
}
