// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { desc, eq } from "drizzle-orm";

import {
  consultationEntitlements,
  reportAccessOrders,
} from "@/drizzle/schema";
import { requireSession } from "@/server/auth/require-session";
import { controlDb } from "@/server/db/control-db";

export async function getMyConsultationsData() {
  const session = await requireSession();

  const consultations = await controlDb
    .select({
      id: consultationEntitlements.id,
      orderId: consultationEntitlements.orderId,
      source: consultationEntitlements.source,
      kind: consultationEntitlements.kind,
      durationMinutes: consultationEntitlements.durationMinutes,
      status: consultationEntitlements.status,
      bookingProvider: consultationEntitlements.bookingProvider,
      bookingReference: consultationEntitlements.bookingReference,
      scheduledStartAt: consultationEntitlements.scheduledStartAt,
      scheduledEndAt: consultationEntitlements.scheduledEndAt,
      meetingUrl: consultationEntitlements.meetingUrl,
      rescheduleUrl: consultationEntitlements.rescheduleUrl,
      cancelUrl: consultationEntitlements.cancelUrl,
      bookedAt: consultationEntitlements.bookedAt,
      completedAt: consultationEntitlements.completedAt,
      createdAt: consultationEntitlements.createdAt,
      orderStatus: reportAccessOrders.status,
      orderMetadata: reportAccessOrders.metadata,
    })
    .from(consultationEntitlements)
    .leftJoin(
      reportAccessOrders,
      eq(reportAccessOrders.id, consultationEntitlements.orderId),
    )
    .where(eq(consultationEntitlements.userId, session.user.id))
    .orderBy(
      desc(consultationEntitlements.scheduledStartAt),
      desc(consultationEntitlements.createdAt),
    );

  return {
    user: {
      email: session.user.email ?? null,
      name: session.user.name ?? null,
    },
    consultations,
  };
}
