// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, desc, eq, isNull } from "drizzle-orm";

import {
  purchaseIntents,
  questionnaireVersions,
  questionnaires,
  reportAccessOrders,
  consultationEntitlements,
} from "@/drizzle/schema";
import { resolveActiveReportAccessProductForOffer } from "@/features/report-access/api/report-access-product-offer.queries";
import { resolveCurrentActiveReportTemplateVersionForSession } from "@/features/report-access/api/report-access.queries";
import { requireSession } from "@/server/auth/require-session";
import { controlDb } from "@/server/db/control-db";
import { getPurchaseFlowConfig } from "../config/purchase-flow.config";
import type { OfferCode, ReportType } from "../types/purchase-flow.types";

export async function resolvePublicQuestionnaireVersionByCode(
  questionnaireCode: string,
) {
  const rows = await controlDb
    .select({
      questionnaireId: questionnaires.id,
      questionnaireCode: questionnaires.code,
      questionnaireName: questionnaires.name,
      questionnaireVersionId: questionnaireVersions.id,
      questionnaireVersionName: questionnaireVersions.name,
    })
    .from(questionnaireVersions)
    .innerJoin(
      questionnaires,
      eq(questionnaires.id, questionnaireVersions.questionnaireId),
    )
    .where(
      and(
        eq(questionnaires.code, questionnaireCode),
        eq(questionnaires.status, "active"),
        eq(questionnaireVersions.status, "active"),
        eq(questionnaireVersions.isPublic, true),
        isNull(questionnaires.deletedAt),
        isNull(questionnaireVersions.deletedAt),
      ),
    )
    .orderBy(desc(questionnaireVersions.updatedAt))
    .limit(1);

  return rows[0] ?? null;
}

export async function resolvePurchaseCombination({
  offerCode,
  reportType,
}: {
  offerCode: OfferCode;
  reportType: ReportType;
}) {
  const config = getPurchaseFlowConfig();
  const questionnaire = await resolvePublicQuestionnaireVersionByCode(
    config.reports[reportType].questionnaireCode,
  );

  if (!questionnaire) {
    return {
      ok: false as const,
      reason: "questionnaire_not_available" as const,
      message: "Wybrany kwestionariusz nie ma aktywnej publicznej wersji.",
    };
  }

  const reportVersion =
    await resolveCurrentActiveReportTemplateVersionForSession({
      questionnaireVersionIds: [questionnaire.questionnaireVersionId],
      expectedKind: "personal",
    });

  if (!reportVersion) {
    return {
      ok: false as const,
      reason: "report_template_not_available" as const,
      message:
        "Dla wybranego kwestionariusza nie ma aktywnego raportu indywidualnego.",
    };
  }

  const product = await resolveActiveReportAccessProductForOffer({
    reportTemplateId: reportVersion.reportTemplateId,
    offerCode,
  });

  if (!product.ok) return product;

  return {
    ok: true as const,
    offer: config.offers[offerCode],
    report: config.reports[reportType],
    questionnaire,
    reportVersion,
    product: product.product,
    b2cOffer: product.b2cOffer,
  };
}

export async function getOwnedPurchaseIntent(
  purchaseIntentId: string,
) {
  const session = await requireSession();

  return (
    (await controlDb.query.purchaseIntents.findFirst({
      where: and(
        eq(purchaseIntents.id, purchaseIntentId),
        eq(purchaseIntents.userId, session.user.id),
        isNull(purchaseIntents.deletedAt),
      ),
    })) ?? null
  );
}

export async function getOwnedPurchaseIntentBySession({
  tenantSlug,
  sessionId,
}: {
  tenantSlug: string;
  sessionId: string;
}) {
  const session = await requireSession();

  const rows = await controlDb
    .select()
    .from(purchaseIntents)
    .where(
      and(
        eq(purchaseIntents.userId, session.user.id),
        eq(purchaseIntents.tenantSlug, tenantSlug),
        eq(purchaseIntents.assessmentSessionId, sessionId),
        isNull(purchaseIntents.deletedAt),
      ),
    )
    .orderBy(desc(purchaseIntents.updatedAt))
    .limit(1);

  return rows[0] ?? null;
}

export async function getOwnedPurchaseIntentForCheckout({
  purchaseIntentId,
  userId,
  tenantSlug,
  sessionId,
}: {
  purchaseIntentId: string;
  userId: string;
  tenantSlug: string;
  sessionId: string;
}) {
  return (
    (await controlDb.query.purchaseIntents.findFirst({
      where: and(
        eq(purchaseIntents.id, purchaseIntentId),
        eq(purchaseIntents.userId, userId),
        eq(purchaseIntents.tenantSlug, tenantSlug),
        eq(purchaseIntents.assessmentSessionId, sessionId),
        isNull(purchaseIntents.deletedAt),
      ),
    })) ?? null
  );
}

export async function getOwnedMarketingOrder(orderId: string) {
  const session = await requireSession();

  const rows = await controlDb
    .select({
      order: reportAccessOrders,
      purchaseIntent: purchaseIntents,
      entitlement: consultationEntitlements,
    })
    .from(reportAccessOrders)
    .leftJoin(
      purchaseIntents,
      eq(purchaseIntents.orderId, reportAccessOrders.id),
    )
    .leftJoin(
      consultationEntitlements,
      eq(consultationEntitlements.orderId, reportAccessOrders.id),
    )
    .where(
      and(
        eq(reportAccessOrders.id, orderId),
        eq(reportAccessOrders.buyerUserId, session.user.id),
        isNull(reportAccessOrders.deletedAt),
      ),
    )
    .limit(1);

  return rows[0] ?? null;
}
