// @generated by install-humanet-values-marketing.mjs
"use server";

import { redirect } from "next/navigation";

import { readAttributionForRequest } from "@/features/attribution";
import { startOrContinuePublicAssessmentSession } from "@/features/my-assessment/api/start-or-continue-public-assessment-session";
import { requireSession } from "@/server/auth/require-session";
import {
  offerCodeSchema,
  reportTypeSchema,
} from "../forms/start-flow.schema";
import { createOrResumePurchaseIntent } from "./purchase-flow.mutations";
import { resolvePurchaseCombination } from "./purchase-flow.queries";

function read(formData: FormData, name: string) {
  const value = formData.get(name);
  return typeof value === "string" ? value.trim() : "";
}

export async function startPurchaseFlowAction(formData: FormData) {
  const session = await requireSession();

  const offerCode = offerCodeSchema.parse(read(formData, "offerCode"));
  const reportType = reportTypeSchema.parse(read(formData, "reportType"));
  const combination = await resolvePurchaseCombination({ offerCode, reportType });

  if (!combination.ok) {
    throw new Error(combination.message);
  }

  const started = await startOrContinuePublicAssessmentSession({
    questionnaireVersionId: combination.questionnaire.questionnaireVersionId,
  });

  const rawSearchParams = JSON.parse(
    read(formData, "attributionSearchParams") || "{}",
  ) as Record<string, string | undefined>;

  const attribution = await readAttributionForRequest(rawSearchParams);

  const intent = await createOrResumePurchaseIntent({
    userId: session.user.id,
    input: {
      offerCode,
      reportType,
      productCode: combination.product.code,
      tenantSlug: started.tenantSlug,
      questionnaireVersionId:
        combination.questionnaire.questionnaireVersionId,
      projectQuestionnaireId: started.projectQuestionnaireId,
      assessmentSessionId: started.sessionId,
      attribution,
    },
  });

  const target = new URL(started.href, "https://values.humanet.me");
  target.searchParams.set("purchaseIntent", intent.id);

  redirect(`${target.pathname}${target.search}`);
}
