// @generated by install-humanet-values-consultations-v5.mjs
import { NextResponse } from "next/server";

import { createOrResumeStandaloneConsultationForCurrentUser } from "@/features/purchase-flow/api/consultation-booking.mutations";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function POST() {
  try {
    const data = await createOrResumeStandaloneConsultationForCurrentUser();

    return NextResponse.json({
      ok: true,
      entitlementId: data.entitlement.id,
      orderId: data.entitlement.orderId,
      durationMinutes: data.entitlement.durationMinutes,
      bookingUrl: data.bookingUrl,
      userEmail: data.user.email,
      userName: data.user.name,
    });
  } catch (error) {
    console.error("CONSULTATION_STANDALONE_CREATE_FAILED", {
      errorName: error instanceof Error ? error.name : "UnknownError",
    });

    return NextResponse.json(
      { ok: false, error: "standalone_consultation_unavailable" },
      { status: 400 },
    );
  }
}
