// @generated by install-humanet-values-marketing.mjs
import "server-only";

import { and, eq, isNull } from "drizzle-orm";

import { reportAccessProducts } from "@/drizzle/schema";
import { controlDb } from "@/server/db/control-db";
import {
  readReportAccessB2cOffer,
  type ReportAccessB2cOfferCode,
} from "../lib/report-access-product-offer";

export async function resolveActiveReportAccessProductForOffer({
  reportTemplateId,
  offerCode,
}: {
  reportTemplateId: string;
  offerCode: ReportAccessB2cOfferCode;
}) {
  const products = await controlDb
    .select()
    .from(reportAccessProducts)
    .where(
      and(
        eq(reportAccessProducts.reportTemplateId, reportTemplateId),
        eq(reportAccessProducts.status, "active"),
        isNull(reportAccessProducts.deletedAt),
      ),
    );

  const matches = products.filter(
    (product) =>
      readReportAccessB2cOffer(product.config)?.offerCode === offerCode,
  );

  if (matches.length === 0) {
    return {
      ok: false as const,
      reason: "b2c_product_not_configured" as const,
      message:
        "Dla wybranego raportu nie skonfigurowano aktywnego produktu dla tego pakietu B2C.",
    };
  }

  if (matches.length > 1) {
    return {
      ok: false as const,
      reason: "b2c_product_ambiguous" as const,
      message:
        "Dla tego raportu i pakietu B2C istnieje więcej niż jeden aktywny produkt. Popraw konfigurację w panelu produktów.",
    };
  }

  return {
    ok: true as const,
    product: matches[0],
    b2cOffer: readReportAccessB2cOffer(matches[0].config)!,
  };
}
