// @generated by install-humanet-values-marketing.mjs
import { MyConsultationsPage } from "@/features/purchase-flow/components/my-consultations-page";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function Page() {
  return <MyConsultationsPage />;
}
