// @generated by install-humanet-values-marketing.mjs
"use client";

import { useEffect } from "react";
import { usePathname, useSearchParams } from "next/navigation";

import { useConsent } from "@/features/consent";
import {
  ATTRIBUTION_COOKIE_NAME,
  parseAttributionCookie,
  writeAttributionCookie,
} from "../lib/attribution-cookie";
import type { AttributionTouch } from "../types/attribution.types";

function readCookie(name: string): string | null {
  const prefix = `${name}=`;
  return (
    document.cookie
      .split(";")
      .map((item) => item.trim())
      .find((item) => item.startsWith(prefix))
      ?.slice(prefix.length) ?? null
  );
}

function value(params: URLSearchParams, name: string): string | null {
  const raw = params.get(name)?.trim();
  return raw || null;
}

export function AttributionCapture() {
  const { consent, hydrated } = useConsent();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  useEffect(() => {
    if (!hydrated || !consent.analytics) return;

    const params = new URLSearchParams(searchParams.toString());
    const hasCampaign =
      params.has("utm_source") ||
      params.has("utm_medium") ||
      params.has("utm_campaign") ||
      params.has("ref") ||
      params.has("partner");

    const current = parseAttributionCookie(
      readCookie(ATTRIBUTION_COOKIE_NAME),
    );

    if (!hasCampaign && current) return;

    const query = params.toString();
    const touch: AttributionTouch = {
      source: value(params, "utm_source"),
      medium: value(params, "utm_medium"),
      campaign: value(params, "utm_campaign"),
      content: value(params, "utm_content"),
      term: value(params, "utm_term"),
      landingPage: `${window.location.origin}${pathname}${query ? `?${query}` : ""}`,
      referrer: document.referrer || null,
      capturedAt: new Date().toISOString(),
      ref: value(params, "ref"),
      partner: value(params, "partner"),
    };

    writeAttributionCookie({
      firstTouch: current?.firstTouch ?? touch,
      lastTouch: hasCampaign ? touch : current?.lastTouch ?? touch,
    });
  }, [consent.analytics, hydrated, pathname, searchParams]);

  return null;
}
