// @generated by install-humanet-values-consultations-v5.mjs
import { NextResponse } from "next/server";
import { z } from "zod";

import { completeOwnedConsultationBooking } from "@/features/purchase-flow/api/consultation-booking.mutations";

const schema = z.object({
  entitlementId: z.string().uuid(),
  uid: z.string().min(1),
  startTime: z.string().min(1),
  endTime: z.string().min(1),
  videoCallUrl: z.string().nullable().optional(),
  eventTypeId: z.number().nullable().optional(),
  status: z.string().nullable().optional(),
});

export async function POST(request: Request) {
  try {
    const body = schema.parse(await request.json());
    await completeOwnedConsultationBooking({
      entitlementId: body.entitlementId,
      uid: body.uid,
      startTime: body.startTime,
      endTime: body.endTime,
      videoCallUrl: body.videoCallUrl,
      eventTypeId: body.eventTypeId,
      eventStatus: body.status,
    });
    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error("CONSULTATION_BOOKING_CLIENT_SYNC_FAILED", {
      errorName: error instanceof Error ? error.name : "UnknownError",
    });

    return NextResponse.json(
      { ok: false, error: "booking_sync_failed" },
      { status: 400 },
    );
  }
}
